- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "security"
  color: "e11d48"
  description: "Pull requests that address a security vulnerability"
