@echo off
setlocal enabledelayedexpansion

echo.
echo =================================================
echo   Olympus -- One-Command Setup (Windows)
echo =================================================
echo.

REM -------------------------------------------------------
REM Change to the directory this batch file lives in
REM -------------------------------------------------------
cd /d "%~dp0"

REM -------------------------------------------------------
REM 1. Check Python 3.10+
REM -------------------------------------------------------
echo [1/7] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found.
    echo        Install Python 3.10+ from https://python.org and re-run.
    pause
    exit /b 1
)

for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYVER=%%v
for /f "tokens=1,2 delims=." %%a in ("%PYVER%") do (
    set PY_MAJOR=%%a
    set PY_MINOR=%%b
)
if %PY_MAJOR% LSS 3 (
    echo ERROR: Python 3.10+ required. Found %PYVER%.
    pause
    exit /b 1
)
if %PY_MAJOR% EQU 3 if %PY_MINOR% LSS 10 (
    echo ERROR: Python 3.10+ required. Found %PYVER%.
    pause
    exit /b 1
)
echo   OK: Python %PYVER%

REM -------------------------------------------------------
REM 2. Start PostgreSQL via Docker (skip if already set)
REM -------------------------------------------------------
echo.
echo [2/7] Checking PostgreSQL...

set DB_USER=olympus
set DB_PASS=olympus

REM If DATABASE_URL is already set in the environment, skip Docker setup
if not "%DATABASE_URL%"=="" (
    echo   OK: DATABASE_URL already set -- skipping Docker PostgreSQL step.
    goto :skip_docker
)

REM Check Docker
docker --version >nul 2>&1
if errorlevel 1 (
    echo   WARN: Docker not found. Skipping PostgreSQL container.
    echo         If you have PostgreSQL running elsewhere, set DATABASE_URL and re-run.
    echo         e.g. set DATABASE_URL=postgresql://user:pass@localhost:5432/olympus
    goto :skip_docker
)

REM Check if container is already running
docker ps --filter "name=olympus-postgres" --format "{{.Names}}" 2>nul | find "olympus-postgres" >nul
if not errorlevel 1 (
    echo   OK: olympus-postgres container already running.
    goto :postgres_ready
)

REM Remove stopped container with same name if it exists
docker ps -a --filter "name=olympus-postgres" --format "{{.Names}}" 2>nul | find "olympus-postgres" >nul
if not errorlevel 1 (
    echo   Removing stopped olympus-postgres container...
    docker rm olympus-postgres >nul 2>&1
)

echo   Starting PostgreSQL container...
docker run --name olympus-postgres ^
    -e POSTGRES_USER=%DB_USER% ^
    -e POSTGRES_PASSWORD=%DB_PASS% ^
    -e POSTGRES_DB=olympus ^
    -p 5432:5432 ^
    -d postgres:16 >nul
if errorlevel 1 (
    echo ERROR: Failed to start PostgreSQL container.
    echo        Check Docker is running and port 5432 is free.
    pause
    exit /b 1
)

echo   Waiting for PostgreSQL to be ready (up to 30 s)...
set READY=0
for /l %%i in (1,1,30) do (
    timeout /t 1 /nobreak >nul
    docker exec olympus-postgres pg_isready -U %DB_USER% -d olympus >nul 2>&1
    if not errorlevel 1 (
        set READY=1
        goto :postgres_ready
    )
)
if %READY%==0 (
    echo ERROR: PostgreSQL did not become ready. Check: docker logs olympus-postgres
    pause
    exit /b 1
)

:postgres_ready
echo   OK: PostgreSQL is ready.

:skip_docker

REM -------------------------------------------------------
REM 3. Set environment variables
REM -------------------------------------------------------
echo.
echo [3/7] Setting environment variables...

if "%DATABASE_URL%"=="" (
    set DATABASE_URL=postgresql://%DB_USER%:%DB_PASS%@localhost:5432/olympus
    echo   OK: DATABASE_URL=postgresql://%DB_USER%:***@localhost:5432/olympus
) else (
    echo   OK: Using existing DATABASE_URL.
)

if "%OLYMPUS_INGEST_SIGNING_KEY%"=="" (
    REM Generate a cryptographically secure random 32-byte key using Python's secrets module
    for /f %%i in ('python -c "import secrets; print(secrets.token_hex(32))"') do (
        set OLYMPUS_INGEST_SIGNING_KEY=%%i
    )
    echo   OK: OLYMPUS_INGEST_SIGNING_KEY generated.
    echo   IMPORTANT: Save this key in your .env file to keep ledger entries verifiable.
) else (
    echo   OK: Using existing OLYMPUS_INGEST_SIGNING_KEY.
)

REM Write .env file if it does not exist
if not exist ".env" (
    (
        echo # Auto-generated by run.bat -- edit as needed.
        echo DATABASE_URL=%DATABASE_URL%
        echo OLYMPUS_INGEST_SIGNING_KEY=%OLYMPUS_INGEST_SIGNING_KEY%
        echo OLYMPUS_DEV_SIGNING_KEY=false
    ) > .env
    echo   OK: .env file written.
) else (
    echo   OK: .env already exists -- not overwriting.
)

REM -------------------------------------------------------
REM 4. Create Python virtual environment
REM -------------------------------------------------------
echo.
echo [4/7] Setting up virtual environment...

if not exist ".venv" (
    python -m venv .venv
    if errorlevel 1 (
        echo ERROR: Failed to create virtual environment.
        pause
        exit /b 1
    )
    echo   OK: Virtual environment created at .venv
) else (
    echo   OK: Virtual environment already exists.
)

REM Activate the virtual environment
call .venv\Scripts\activate.bat
if errorlevel 1 (
    echo ERROR: Could not activate virtual environment.
    pause
    exit /b 1
)
echo   OK: Virtual environment activated.

REM -------------------------------------------------------
REM 5. Install dependencies
REM -------------------------------------------------------
echo.
echo [5/7] Installing dependencies (may take a few minutes)...

python -m pip install --upgrade pip --quiet
if errorlevel 1 (
    echo WARN: pip upgrade failed, continuing with existing version...
)

REM Install the package with its dev extras directly from pyproject.toml.
REM This avoids hash-checking conflicts from requirements.txt when doing
REM editable installs.
pip install -e ".[dev]" --quiet
if errorlevel 1 (
    echo   Retrying without dev extras...
    pip install -e . --quiet
    if errorlevel 1 (
        echo ERROR: Dependency installation failed.
        echo        Try running: pip install -e ".[dev]"
        pause
        exit /b 1
    )
)
echo   OK: Dependencies installed.

REM -------------------------------------------------------
REM 6. Run database migrations
REM -------------------------------------------------------
echo.
echo [6/7] Running Alembic database migrations...

python -m alembic upgrade head
if errorlevel 1 (
    echo ERROR: Alembic migration failed.
    echo        Make sure DATABASE_URL is correct and PostgreSQL is accessible.
    echo        DATABASE_URL=%DATABASE_URL%
    pause
    exit /b 1
)
echo   OK: Database schema is up to date.

REM -------------------------------------------------------
REM 7. Start the API server
REM -------------------------------------------------------
echo.
echo [7/7] Starting Olympus API server...
echo.
echo =================================================
echo   Olympus is ready!
echo.
echo   API:      http://localhost:8000
echo   API Docs: http://localhost:8000/docs
echo   Database: %DATABASE_URL%
echo.
echo   Press Ctrl+C to stop.
echo =================================================
echo.

python -m uvicorn api.app:app --reload --host 0.0.0.0 --port 8000
