// SPDX-FileCopyrightText: 2026 Olympus Contributors
// SPDX-License-Identifier: Apache-2.0

//
// Witness-level soundness tests for the `federation_quorum` circuit.
//
// These exercise the CIRCUIT, not the host witness builder. circom's generated
// WASM evaluates every `===` as a runtime assertion, so an unsatisfiable input
// aborts witness generation — which makes a constraint testable with nothing
// but a compiled `.wasm`. No ptau, no zkey, no trusted setup. That matters
// because `federation_quorum`'s ceremony has not been run: its vkey and zkey
// are placeholders, so a prove/verify round-trip is not available and these
// tests would otherwise have no way to run at all.
//
// Asserting *why* a case was rejected
// -----------------------------------
// `assert.throws(...)` alone would pass on any failure, including an unrelated
// early abort — the exact defect class CLAUDE.md's negative-test rule targets.
// circom reports `Error in template <T> line: <N>`, so each case below names
// the template AND a pattern the source line at N must match. The line is
// resolved from the `.circom` source at run time rather than hardcoded, so
// editing the circuit moves the assertion with it instead of rotting it.
//
// Fixtures
// --------
// Committed under `proofs/test_inputs/quorum_fixtures/`, generated by
// `zk::witness::quorum::tests::emit_circom_fixtures_for_the_witness_harness`.
// The negative cases need REAL BJJ-EdDSA signatures — a case meant to trip the
// distinctness constraint would otherwise trip the signature check and prove
// nothing — and there is no `circomlibjs` here to produce them. Committing the
// generated inputs (the `clients/python/tests/vectors.json` pattern) is what
// lets this run in a CI job with circom + Node but no Tauri/GTK Rust build.
// Regenerate with:
//
//   cargo test --no-default-features --features prover,quorum-circuit \
//       --lib zk::witness::quorum
//
// The compiled circuit still has to exist (`pnpm --dir proofs circom:build`).
// When a prerequisite is missing these skip with a reason — unless
// `OLYMPUS_REQUIRE_CIRCUIT_TESTS=1`, which makes it a hard failure. The
// `formal circuit verification (circomspect)` CI job compiles the circuit and
// sets that variable; the general-purpose `proof helper tests` job does not and
// keeps skipping. A silent skip where the tests were meant to run would report
// green while testing nothing — the same defect class these tests exist to
// catch.

"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { test, describe } = require("node:test");

const proofsDir = path.resolve(__dirname, "..");
const wasmPath = path.join(proofsDir, "build", "federation_quorum_js", "federation_quorum.wasm");
const fixtureDir = path.join(proofsDir, "test_inputs", "quorum_fixtures");
const snarkjsCli = path.join(proofsDir, "node_modules", "snarkjs", "build", "cli.cjs");

// Where each circom template's source lives, for resolving a reported line.
const TEMPLATE_SOURCES = {
  FederationQuorum: path.join(proofsDir, "circuits", "federation_quorum.circom"),
  BabyCheck: path.join(proofsDir, "vendor", "circomlib", "circuits", "babyjub.circom"),
  Num2Bits: path.join(proofsDir, "vendor", "circomlib", "circuits", "bitify.circom"),
};

/**
 * Every negative fixture, with the constraint it must die on.
 *
 * `reproducesPreFix` records whether the case was ACCEPTED by the circuit as it
 * stood before this fix — i.e. whether it demonstrates a real soundness break
 * or merely guards a check that was already effective by accident. Measured by
 * replaying each fixture against a build of the pre-fix circuit, not assumed.
 * Keeping the distinction visible stops a regression guard from being read as a
 * vulnerability repro.
 */
const NEGATIVE_CASES = [
  {
    fixture: "n1_m5_all_padding_enabled",
    finding: "OLY-M5",
    template: "FederationQuorum",
    linePattern: /enabled\[i\]\s*\*\s*samePoint\[p\]\s*===\s*0/,
    reproducesPreFix: true,
    why: "one signer padded to N, every padding slot flipped on, one signature reused",
  },
  {
    fixture: "n2_m5_padding_copy_enabled",
    finding: "OLY-M5",
    template: "FederationQuorum",
    linePattern: /enabled\[i\]\s*\*\s*samePoint\[p\]\s*===\s*0/,
    reproducesPreFix: true,
    why: "the real slot disabled and a padding copy of it enabled instead",
  },
  {
    fixture: "n3_threshold_256",
    finding: "threshold range",
    template: "Num2Bits",
    linePattern: /lc1\s*===\s*in/,
    reproducesPreFix: false,
    why: "threshold = 256 exceeds the 8-bit comparator; pre-fix this was already refused by geq (256 > validCount), so it is a range-check guard, not a break",
  },
  {
    fixture: "n4_threshold_field_max",
    finding: "threshold range",
    template: "Num2Bits",
    linePattern: /lc1\s*===\s*in/,
    reproducesPreFix: true,
    why: "threshold = r-1 wrapped GreaterEqThan(8) and satisfied it vacuously",
  },
  {
    fixture: "n5_threshold_zero",
    finding: "threshold range",
    template: "FederationQuorum",
    linePattern: /thresholdIsZero\.out\s*===\s*0/,
    reproducesPreFix: true,
    why: "threshold = 0 made the quorum trivially satisfied",
  },
  {
    fixture: "n6_off_curve_enabled_slot",
    finding: "OLY-L12",
    template: "BabyCheck",
    linePattern: /a\s*\*\s*x2\s*\+\s*y2\s*===\s*1\s*\+\s*d\s*\*\s*x2\s*\*\s*y2/,
    reproducesPreFix: false,
    why: "off-curve key on an ENABLED slot; pre-fix the EdDSA equality caught it incidentally, so this only upgrades the rejection reason",
  },
  {
    fixture: "n7_off_curve_disabled_slot",
    finding: "OLY-L12",
    template: "BabyCheck",
    linePattern: /a\s*\*\s*x2\s*\+\s*y2\s*===\s*1\s*\+\s*d\s*\*\s*x2\s*\*\s*y2/,
    reproducesPreFix: true,
    why: "off-curve key on a DISABLED padding slot — unchecked pre-fix, since every circomlib check there is enabled-gated",
  },
];

const POSITIVE_CASES = [
  {
    fixture: "p1_three_of_three",
    why: "three distinct signers, all three co-sign",
  },
  {
    fixture: "p2_padded_single_signer",
    why: "one signer padded to N — duplicate keys on DISABLED slots stay legal, which is what the padding produces",
  },
];

function missingPrerequisite() {
  if (!fs.existsSync(wasmPath)) {
    return `compiled circuit not found at ${path.relative(proofsDir, wasmPath)} — run \`pnpm --dir proofs circom:build\``;
  }
  if (!fs.existsSync(fixtureDir)) {
    return `fixtures not found at ${path.relative(proofsDir, fixtureDir)} — run the Rust emitter (see header)`;
  }
  if (!fs.existsSync(snarkjsCli)) {
    return "snarkjs not installed — run `pnpm install` in proofs/";
  }
  return null;
}

/** Run witness generation. Returns `{ ok: true }` or `{ ok: false, stderr }`. */
function calculateWitness(fixtureName) {
  const input = path.join(fixtureDir, `${fixtureName}.json`);
  assert.ok(fs.existsSync(input), `missing fixture ${fixtureName}.json`);
  // Witness output goes to the gitignored build dir — never next to the
  // committed fixtures.
  const outDir = path.join(proofsDir, "build", "quorum_witnesses");
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, `${fixtureName}.wtns`);
  const result = spawnSync(
    process.execPath,
    [snarkjsCli, "wtns", "calculate", wasmPath, input, out],
    {
      cwd: proofsDir,
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
      timeout: 300_000,
    },
  );
  assert.equal(result.error, undefined, result.error?.message);
  if (result.status === 0) return { ok: true };
  return { ok: false, stderr: `${result.stderr || ""}${result.stdout || ""}` };
}

/**
 * Pull `template` + `line` out of circom's abort, then return the source line
 * it points at. Throws (failing the test) if the message is not the expected
 * shape — an unparseable abort must not be silently treated as a pass.
 */
function resolveFailingConstraint(stderr) {
  const m = stderr.match(/Error in template (\w+?)(?:_\d+)? line: (\d+)/);
  assert.ok(
    m,
    `could not parse a template/line out of circom's abort — the case may have failed for an unrelated reason:\n${stderr}`,
  );
  const [, template, lineNo] = m;
  const source = TEMPLATE_SOURCES[template];
  assert.ok(source, `no source mapping for template ${template}`);
  const lines = fs.readFileSync(source, "utf8").split(/\r?\n/);
  const text = (lines[Number(lineNo) - 1] ?? "").trim();
  return { template, lineNo: Number(lineNo), text };
}

describe("federation_quorum circuit constraints", () => {
  // node:test treats ANY non-undefined `skip` — including `null` — as a skip,
  // so the option is only passed when there is actually a reason to skip.
  // Spreading `{}` otherwise is what keeps these tests from silently reporting
  // green without running.
  const reason = missingPrerequisite();
  if (reason && process.env.OLYMPUS_REQUIRE_CIRCUIT_TESTS === "1") {
    // Set by the CI job that DOES compile the circuit. There, a skip would
    // report green while testing nothing — the exact failure class these tests
    // exist to catch — so a missing prerequisite is fatal instead. Deliberately
    // not keyed on `CI`: the general-purpose `proof helper tests` job runs
    // `node --test` without circom, and must keep skipping rather than fail.
    throw new Error(`federation_quorum circuit tests were required but cannot run: ${reason}`);
  }
  const skip = reason ? { skip: reason } : {};

  for (const c of POSITIVE_CASES) {
    test(`accepts ${c.fixture}: ${c.why}`, skip, () => {
      const r = calculateWitness(c.fixture);
      assert.ok(r.ok, `witness generation must succeed but failed:\n${r.stderr}`);
    });
  }

  for (const c of NEGATIVE_CASES) {
    const label = c.reproducesPreFix ? `${c.finding} repro` : `${c.finding} regression guard`;
    test(`rejects ${c.fixture} [${label}]: ${c.why}`, skip, () => {
      const r = calculateWitness(c.fixture);
      assert.ok(r.ok === false, "witness generation must fail for this input");

      const { template, lineNo, text } = resolveFailingConstraint(r.stderr);
      assert.equal(
        template,
        c.template,
        `expected the abort in template ${c.template}, got ${template} (line ${lineNo}: ${text})`,
      );
      assert.match(
        text,
        c.linePattern,
        `template ${template} line ${lineNo} is "${text}", which is not the constraint this test claims to exercise`,
      );
    });
  }
});
