// This file is @generated by prost-build.
/// Request to update (insert or modify) a record
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateRequest {
    /// Shard identifier (e.g., "watauga:2025:budget")
    #[prost(string, tag = "1")]
    pub shard_id: ::prost::alloc::string::String,
    /// Record key components (type, id, version, etc.)
    #[prost(message, optional, tag = "2")]
    pub record_key: ::core::option::Option<RecordKey>,
    /// Canonicalized record content (already canonicalized)
    #[prost(bytes = "vec", tag = "3")]
    pub canonical_content: ::prost::alloc::vec::Vec<u8>,
}
/// Response from update operation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateResponse {
    /// The new root hash after update
    #[prost(bytes = "vec", tag = "1")]
    pub new_root: ::prost::alloc::vec::Vec<u8>,
    /// The global key that was computed
    #[prost(bytes = "vec", tag = "2")]
    pub global_key: ::prost::alloc::vec::Vec<u8>,
    /// The leaf value hash that was stored
    #[prost(bytes = "vec", tag = "3")]
    pub leaf_value_hash: ::prost::alloc::vec::Vec<u8>,
    /// SMT node deltas (for persistence)
    #[prost(message, repeated, tag = "4")]
    pub deltas: ::prost::alloc::vec::Vec<SmtNodeDelta>,
    /// Tree size after this update (number of non-empty leaves)
    #[prost(uint64, tag = "5")]
    pub tree_size: u64,
}
/// Record key components
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecordKey {
    /// Record type (e.g., "doc", "dataset", "appeal")
    #[prost(string, tag = "1")]
    pub record_type: ::prost::alloc::string::String,
    /// Record ID
    #[prost(string, tag = "2")]
    pub record_id: ::prost::alloc::string::String,
    /// Version (optional)
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    /// Additional metadata (for future extensibility)
    #[prost(map = "string, string", tag = "4")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// SMT node delta for persistence
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SmtNodeDelta {
    /// Path to the node (256 bits as bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub path: ::prost::alloc::vec::Vec<u8>,
    /// Level in the tree (0-255)
    #[prost(uint32, tag = "2")]
    pub level: u32,
    /// New hash value
    #[prost(bytes = "vec", tag = "3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
/// Request to prove inclusion
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveInclusionRequest {
    /// Shard identifier
    #[prost(string, tag = "1")]
    pub shard_id: ::prost::alloc::string::String,
    /// Record key
    #[prost(message, optional, tag = "2")]
    pub record_key: ::core::option::Option<RecordKey>,
    /// Root hash to prove against (optional, uses current if not specified)
    #[prost(bytes = "vec", tag = "3")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Response with inclusion proof
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveInclusionResponse {
    /// The global key
    #[prost(bytes = "vec", tag = "1")]
    pub global_key: ::prost::alloc::vec::Vec<u8>,
    /// The leaf value hash
    #[prost(bytes = "vec", tag = "2")]
    pub value_hash: ::prost::alloc::vec::Vec<u8>,
    /// Sibling hashes along the path (256 siblings)
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub siblings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Root hash
    #[prost(bytes = "vec", tag = "4")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Request to verify inclusion
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyInclusionRequest {
    /// Global key
    #[prost(bytes = "vec", tag = "1")]
    pub global_key: ::prost::alloc::vec::Vec<u8>,
    /// Leaf value hash
    #[prost(bytes = "vec", tag = "2")]
    pub value_hash: ::prost::alloc::vec::Vec<u8>,
    /// Sibling hashes
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub siblings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Root hash to verify against
    #[prost(bytes = "vec", tag = "4")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Response from verification
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyInclusionResponse {
    /// Whether the proof is valid
    #[prost(bool, tag = "1")]
    pub valid: bool,
    /// Error message if invalid
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Request to prove non-inclusion
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveNonInclusionRequest {
    /// Shard identifier
    #[prost(string, tag = "1")]
    pub shard_id: ::prost::alloc::string::String,
    /// Record key
    #[prost(message, optional, tag = "2")]
    pub record_key: ::core::option::Option<RecordKey>,
    /// Root hash to prove against (optional, uses current if not specified)
    #[prost(bytes = "vec", tag = "3")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Response with non-inclusion proof
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveNonInclusionResponse {
    /// The global key
    #[prost(bytes = "vec", tag = "1")]
    pub global_key: ::prost::alloc::vec::Vec<u8>,
    /// Sibling hashes along the path to empty leaf
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub siblings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Root hash
    #[prost(bytes = "vec", tag = "3")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Request to verify non-inclusion
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyNonInclusionRequest {
    /// Global key
    #[prost(bytes = "vec", tag = "1")]
    pub global_key: ::prost::alloc::vec::Vec<u8>,
    /// Sibling hashes
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub siblings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Root hash to verify against
    #[prost(bytes = "vec", tag = "3")]
    pub root: ::prost::alloc::vec::Vec<u8>,
}
/// Response from non-inclusion verification
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyNonInclusionResponse {
    /// Whether the proof is valid
    #[prost(bool, tag = "1")]
    pub valid: bool,
    /// Error message if invalid
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Request to canonicalize content
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalizeRequest {
    /// Content type (e.g., "json", "html", "xml")
    #[prost(string, tag = "1")]
    pub content_type: ::prost::alloc::string::String,
    /// Raw content
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
/// Response with canonicalized content
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CanonicalizeResponse {
    /// Canonicalized content
    #[prost(bytes = "vec", tag = "1")]
    pub canonical_content: ::prost::alloc::vec::Vec<u8>,
    /// Hash of canonicalized content
    #[prost(bytes = "vec", tag = "2")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
}
/// Request to get current root
///
/// No parameters needed
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRootRequest {}
/// Response with current root
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRootResponse {
    /// Current root hash
    #[prost(bytes = "vec", tag = "1")]
    pub root: ::prost::alloc::vec::Vec<u8>,
    /// Tree size (number of non-empty leaves)
    #[prost(uint64, tag = "2")]
    pub tree_size: u64,
}
/// Request to sign a root
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignRootRequest {
    /// Root hash to sign
    #[prost(bytes = "vec", tag = "1")]
    pub root: ::prost::alloc::vec::Vec<u8>,
    /// Tree size at the time of signing
    #[prost(uint64, tag = "2")]
    pub tree_size: u64,
    /// Additional context (e.g., shard_id, record_id)
    #[prost(map = "string, string", tag = "3")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Response with signature
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignRootResponse {
    /// Ed25519 signature
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Public key used for signing
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
/// Generated server implementations.
pub mod cdhs_smf_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CdhsSmfServiceServer.
    #[async_trait]
    pub trait CdhsSmfService: Send + Sync + 'static {
        /// Insert or update a record in the global SMT
        async fn update(
            &self,
            request: tonic::Request<super::UpdateRequest>,
        ) -> std::result::Result<tonic::Response<super::UpdateResponse>, tonic::Status>;
        /// Generate an inclusion proof for a key
        async fn prove_inclusion(
            &self,
            request: tonic::Request<super::ProveInclusionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveInclusionResponse>,
            tonic::Status,
        >;
        /// Verify an inclusion proof
        async fn verify_inclusion(
            &self,
            request: tonic::Request<super::VerifyInclusionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyInclusionResponse>,
            tonic::Status,
        >;
        /// Generate a non-inclusion proof for a key
        async fn prove_non_inclusion(
            &self,
            request: tonic::Request<super::ProveNonInclusionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveNonInclusionResponse>,
            tonic::Status,
        >;
        /// Verify a non-inclusion proof
        async fn verify_non_inclusion(
            &self,
            request: tonic::Request<super::VerifyNonInclusionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyNonInclusionResponse>,
            tonic::Status,
        >;
        /// Canonicalize a record (for consistency)
        async fn canonicalize(
            &self,
            request: tonic::Request<super::CanonicalizeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CanonicalizeResponse>,
            tonic::Status,
        >;
        /// Get the current root hash
        async fn get_root(
            &self,
            request: tonic::Request<super::GetRootRequest>,
        ) -> std::result::Result<tonic::Response<super::GetRootResponse>, tonic::Status>;
        /// Sign a root hash with Ed25519
        async fn sign_root(
            &self,
            request: tonic::Request<super::SignRootRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SignRootResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CdhsSmfServiceServer<T: CdhsSmfService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: CdhsSmfService> CdhsSmfServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CdhsSmfServiceServer<T>
    where
        T: CdhsSmfService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/olympus.cdhs_smf.v1.CdhsSmfService/Update" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::UpdateRequest>
                    for UpdateSvc<T> {
                        type Response = super::UpdateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::update(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = UpdateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/ProveInclusion" => {
                    #[allow(non_camel_case_types)]
                    struct ProveInclusionSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::ProveInclusionRequest>
                    for ProveInclusionSvc<T> {
                        type Response = super::ProveInclusionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProveInclusionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::prove_inclusion(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ProveInclusionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyInclusion" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyInclusionSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::VerifyInclusionRequest>
                    for VerifyInclusionSvc<T> {
                        type Response = super::VerifyInclusionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyInclusionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::verify_inclusion(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = VerifyInclusionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/ProveNonInclusion" => {
                    #[allow(non_camel_case_types)]
                    struct ProveNonInclusionSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::ProveNonInclusionRequest>
                    for ProveNonInclusionSvc<T> {
                        type Response = super::ProveNonInclusionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProveNonInclusionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::prove_non_inclusion(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ProveNonInclusionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyNonInclusion" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyNonInclusionSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::VerifyNonInclusionRequest>
                    for VerifyNonInclusionSvc<T> {
                        type Response = super::VerifyNonInclusionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyNonInclusionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::verify_non_inclusion(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = VerifyNonInclusionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/Canonicalize" => {
                    #[allow(non_camel_case_types)]
                    struct CanonicalizeSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::CanonicalizeRequest>
                    for CanonicalizeSvc<T> {
                        type Response = super::CanonicalizeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CanonicalizeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::canonicalize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CanonicalizeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/GetRoot" => {
                    #[allow(non_camel_case_types)]
                    struct GetRootSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::GetRootRequest>
                    for GetRootSvc<T> {
                        type Response = super::GetRootResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRootRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::get_root(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetRootSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/olympus.cdhs_smf.v1.CdhsSmfService/SignRoot" => {
                    #[allow(non_camel_case_types)]
                    struct SignRootSvc<T: CdhsSmfService>(pub Arc<T>);
                    impl<
                        T: CdhsSmfService,
                    > tonic::server::UnaryService<super::SignRootRequest>
                    for SignRootSvc<T> {
                        type Response = super::SignRootResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SignRootRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CdhsSmfService>::sign_root(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SignRootSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: CdhsSmfService> Clone for CdhsSmfServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: CdhsSmfService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: CdhsSmfService> tonic::server::NamedService for CdhsSmfServiceServer<T> {
        const NAME: &'static str = "olympus.cdhs_smf.v1.CdhsSmfService";
    }
}
