//! Thin wrapper around `ark-groth16` verification.
//!
//! Loads vkey once (cached in `OnceLock`) and verifies proofs without any
//! Node.js subprocess or JSON-IPC round-trip.

use std::path::Path;
use std::sync::OnceLock;

use ark_bn254::{Bn254, Fr};
use ark_groth16::{prepare_verifying_key, Groth16, PreparedVerifyingKey, VerifyingKey};
use ark_snark::SNARK;
use thiserror::Error;

use super::proof::{parse_proof_json, ProofError};
use super::vkey::{load_vkey, VkeyError};

#[derive(Debug, Error)]
pub enum VerifyError {
    #[error("Vkey load error: {0}")]
    Vkey(#[from] VkeyError),
    #[error("Proof parse error: {0}")]
    Proof(#[from] ProofError),
    #[error("Groth16 verification failed (proof is invalid)")]
    Invalid,
    #[error("Groth16 verifier error: {0}")]
    Ark(String),
}

/// A prepared (preprocessed) verifying key for one circuit.
pub struct CircuitVerifier {
    pvk: PreparedVerifyingKey<Bn254>,
}

impl CircuitVerifier {
    /// Load from a snarkjs vkey JSON file and preprocess.
    pub fn from_file(path: impl AsRef<Path>) -> Result<Self, VerifyError> {
        let vk = load_vkey(path)?;
        Ok(Self { pvk: prepare_verifying_key(&vk) })
    }

    /// Load from an embedded JSON string (e.g. `include_str!(...)`).
    pub fn from_json(json: &str) -> Result<Self, VerifyError> {
        let vk = super::vkey::parse_vkey_json(json)?;
        Ok(Self { pvk: prepare_verifying_key(&vk) })
    }

    /// Verify a snarkjs Groth16 proof JSON against a slice of public signals.
    ///
    /// `proof_json` — the `proof` object from snarkjs (not the full prove output).
    /// `public_signals` — Fr elements in the same order as the circuit's public inputs.
    pub fn verify(&self, proof_json: &str, public_signals: &[Fr]) -> Result<bool, VerifyError> {
        let proof = parse_proof_json(proof_json)?;
        self.verify_proof(&proof, public_signals)
    }

    /// Verify an already-parsed Groth16 proof directly. Use this when the
    /// proof was generated by the native Rust prover (`zk::prove`) — there's
    /// no JSON round-trip in that path.
    pub fn verify_proof(
        &self,
        proof: &ark_groth16::Proof<Bn254>,
        public_signals: &[Fr],
    ) -> Result<bool, VerifyError> {
        Groth16::<Bn254>::verify_with_processed_vk(&self.pvk, public_signals, proof)
            .map_err(|e| VerifyError::Ark(e.to_string()))
    }
}

// ── Embedded verification keys ─────────────────────────────────────────────────
// Keys are embedded at compile time so the release binary needs no external files.

static EXISTENCE_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();
static NON_EXISTENCE_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();
static REDACTION_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();

const EXISTENCE_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/document_existence_vkey.json");
const NON_EXISTENCE_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/non_existence_vkey.json");
const REDACTION_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/redaction_validity_vkey.json");

// `OnceLock::get_or_try_init` is nightly (rust-lang/rust#109737). Stable
// equivalent: try-init eagerly, store on success, return a fresh error on
// failure. The verifier initialisation is deterministic (parses an embedded
// JSON constant), so the only way it can fail is a corrupt build artifact —
// which would fail on every call regardless of caching, so re-running the
// init on a previous failure is benign.
fn get_or_init_verifier(
    slot: &'static OnceLock<CircuitVerifier>,
    vkey_json: &'static str,
) -> Result<&'static CircuitVerifier, VerifyError> {
    if let Some(v) = slot.get() {
        return Ok(v);
    }
    let verifier = CircuitVerifier::from_json(vkey_json)?;
    // get_or_init takes a closure that yields the value; we already have
    // ours, so close over it. If another thread won the race the closure
    // is never called.
    Ok(slot.get_or_init(|| verifier))
}

pub fn existence_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&EXISTENCE_VERIFIER, EXISTENCE_VKEY_JSON)
}

pub fn non_existence_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&NON_EXISTENCE_VERIFIER, NON_EXISTENCE_VKEY_JSON)
}

pub fn redaction_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&REDACTION_VERIFIER, REDACTION_VKEY_JSON)
}
