//! Thin wrapper around `ark-groth16` verification.
//!
//! Loads vkey once (cached in `OnceLock`) and verifies proofs without any
//! Node.js subprocess or JSON-IPC round-trip.

use std::path::Path;
use std::sync::OnceLock;

use ark_bn254::{Bn254, Fr};
use ark_groth16::{prepare_verifying_key, Groth16, PreparedVerifyingKey, VerifyingKey};
use ark_snark::SNARK;
use thiserror::Error;

use super::proof::{parse_proof_json, ProofError};
use super::vkey::{load_vkey, VkeyError};

#[derive(Debug, Error)]
pub enum VerifyError {
    #[error("Vkey load error: {0}")]
    Vkey(#[from] VkeyError),
    #[error("Proof parse error: {0}")]
    Proof(#[from] ProofError),
    #[error("Groth16 verification failed (proof is invalid)")]
    Invalid,
    #[error("Groth16 verifier error: {0}")]
    Ark(String),
}

/// A prepared (preprocessed) verifying key for one circuit.
pub struct CircuitVerifier {
    pvk: PreparedVerifyingKey<Bn254>,
}

impl CircuitVerifier {
    /// Load from a snarkjs vkey JSON file and preprocess.
    pub fn from_file(path: impl AsRef<Path>) -> Result<Self, VerifyError> {
        let vk = load_vkey(path)?;
        Ok(Self {
            pvk: prepare_verifying_key(&vk),
        })
    }

    /// Load from an embedded JSON string (e.g. `include_str!(...)`).
    pub fn from_json(json: &str) -> Result<Self, VerifyError> {
        let vk = super::vkey::parse_vkey_json(json)?;
        Ok(Self {
            pvk: prepare_verifying_key(&vk),
        })
    }

    /// Verify a snarkjs Groth16 proof JSON against a slice of public signals.
    ///
    /// `proof_json` — the `proof` object from snarkjs (not the full prove output).
    /// `public_signals` — Fr elements in the same order as the circuit's public inputs.
    pub fn verify(&self, proof_json: &str, public_signals: &[Fr]) -> Result<bool, VerifyError> {
        let proof = parse_proof_json(proof_json)?;
        self.verify_proof(&proof, public_signals)
    }

    /// Verify an already-parsed Groth16 proof directly. Use this when the
    /// proof was generated by the native Rust prover (`zk::prove`) — there's
    /// no JSON round-trip in that path.
    pub fn verify_proof(
        &self,
        proof: &ark_groth16::Proof<Bn254>,
        public_signals: &[Fr],
    ) -> Result<bool, VerifyError> {
        Groth16::<Bn254>::verify_with_processed_vk(&self.pvk, public_signals, proof)
            .map_err(|e| VerifyError::Ark(e.to_string()))
    }
}

// ── Embedded verification keys ─────────────────────────────────────────────────
// Keys are embedded at compile time so the release binary needs no external files.

static EXISTENCE_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();
static NON_EXISTENCE_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();
static UNIFIED_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();
#[cfg(feature = "quorum-circuit")]
static FEDERATION_QUORUM_VERIFIER: OnceLock<CircuitVerifier> = OnceLock::new();

const EXISTENCE_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/document_existence_vkey.json");
const NON_EXISTENCE_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/non_existence_vkey.json");
const UNIFIED_VKEY_JSON: &str = include_str!(
    "../../../proofs/keys/verification_keys/unified_canonicalization_inclusion_root_sign_vkey.json"
);
#[cfg(feature = "quorum-circuit")]
const FEDERATION_QUORUM_VKEY_JSON: &str =
    include_str!("../../../proofs/keys/verification_keys/federation_quorum_vkey.json");

// ── Embedded ceremony manifests (audit CEREMONY_INTEGRITY.md #1) ─────────
// One per circuit, embedded at compile time alongside the vkey JSON it
// covers. build.rs already asserted `manifest.artifacts.vkey.blake3 ==
// blake3(vkey.json)` at compile time, so by the time these constants
// are deserialised at runtime, the (manifest ↔ vkey) pairing is
// guaranteed atomic. The runtime check in
// `load_proving_key_with_manifest` extends the same guarantee to the
// `.ark.zkey` file the prover loads from disk.
pub const EXISTENCE_MANIFEST_JSON: &str =
    include_str!("../../../proofs/keys/manifests/document_existence_manifest.json");
pub const NON_EXISTENCE_MANIFEST_JSON: &str =
    include_str!("../../../proofs/keys/manifests/non_existence_manifest.json");
pub const UNIFIED_MANIFEST_JSON: &str = include_str!(
    "../../../proofs/keys/manifests/unified_canonicalization_inclusion_root_sign_manifest.json"
);
#[cfg(feature = "quorum-circuit")]
pub const FEDERATION_QUORUM_MANIFEST_JSON: &str =
    include_str!("../../../proofs/keys/manifests/federation_quorum_manifest.json");

// `OnceLock::get_or_try_init` is nightly (rust-lang/rust#109737). Stable
// equivalent: try-init eagerly, store on success, return a fresh error on
// failure. The verifier initialisation is deterministic (parses an embedded
// JSON constant), so the only way it can fail is a corrupt build artifact —
// which would fail on every call regardless of caching, so re-running the
// init on a previous failure is benign.
fn get_or_init_verifier(
    slot: &'static OnceLock<CircuitVerifier>,
    vkey_json: &'static str,
) -> Result<&'static CircuitVerifier, VerifyError> {
    if let Some(v) = slot.get() {
        return Ok(v);
    }
    let verifier = CircuitVerifier::from_json(vkey_json)?;
    // get_or_init takes a closure that yields the value; we already have
    // ours, so close over it. If another thread won the race the closure
    // is never called.
    Ok(slot.get_or_init(|| verifier))
}

pub fn existence_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&EXISTENCE_VERIFIER, EXISTENCE_VKEY_JSON)
}

pub fn non_existence_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&NON_EXISTENCE_VERIFIER, NON_EXISTENCE_VKEY_JSON)
}

pub fn unified_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&UNIFIED_VERIFIER, UNIFIED_VKEY_JSON)
}

/// Verifier for the `federation_quorum` circuit. Like the unified circuit, its
/// vkey is produced by a trusted-setup ceremony and is gitignored until then;
/// `build.rs` drops a placeholder, so this returns `Err` (placeholder JSON
/// fails to parse as a vkey) until the ceremony has been run and a real vkey
/// staged. Fails closed — a quorum credential's ZK attestation can't be
/// verified against a placeholder. Gated behind `quorum-circuit` (next-phase).
#[cfg(feature = "quorum-circuit")]
pub fn federation_quorum_verifier() -> Result<&'static CircuitVerifier, VerifyError> {
    get_or_init_verifier(&FEDERATION_QUORUM_VERIFIER, FEDERATION_QUORUM_VKEY_JSON)
}

/// Audit H-2: when `signals[tree_size_idx]` is zero, the in-circuit
/// `leafIndex < treeSize` bounds check is disabled. Off-chain verifiers
/// must reject this case unless `signals[root_idx]` equals the
/// precomputed empty-tree root — otherwise a caller can submit
/// `treeSize=0` together with any non-empty root and an arbitrary
/// `leafIndex < 2^depth` and the pairing check will pass for an
/// out-of-range inclusion claim.
///
/// Pure helper returning `Result<(), String>` so both the HTTP
/// `/zk/verify` route (which wraps `String` → `ApiError`) and the
/// federation `verify_checkpoint_proof` path (which returns
/// `Result<bool, String>` already) can share a single implementation —
/// red-team F-RT-1 was a forgotten reuse of the HTTP-only helper that
/// previously lived in `api::zk::mod`.
///
/// This guard only applies to circuits whose public-signal vector
/// contains `(root, …, treeSize)` — currently `document_existence`
/// (`[root, leafIndex, treeSize]`) and the unified circuit
/// (`[canonicalHash, merkleRoot, ledgerRoot, treeSize]`, with `root_idx`
/// pointing at `merkleRoot` because the in-circuit bounds check is gated
/// on the merkleRoot's tree, not the envelope ledger).
pub fn enforce_empty_tree_invariant(
    signals: &[ark_bn254::Fr],
    root_idx: usize,
    tree_size_idx: usize,
) -> Result<(), String> {
    use ark_ff::Zero;
    let Some(tree_size) = signals.get(tree_size_idx) else {
        return Err("public signals missing treeSize".to_owned());
    };
    if !tree_size.is_zero() {
        return Ok(());
    }
    let Some(root) = signals.get(root_idx) else {
        return Err("public signals missing root".to_owned());
    };
    let empty = crate::zk::poseidon::empty_doc_existence_root()
        .map_err(|e| format!("empty-tree root resolve: {e}"))?;
    if *root != empty {
        return Err("treeSize=0 requires root == empty-tree root (audit H-2): \
             rejecting inclusion proof against a non-empty root with treeSize=0"
            .to_owned());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_json_rejects_malformed_json() {
        let r = CircuitVerifier::from_json("not json");
        // The vkey parser bubbles up a Json or Field error — either way
        // a VerifyError, not Ok.
        assert!(r.is_err());
    }

    #[test]
    fn existence_verifier_loads_from_embedded_vkey() {
        assert!(existence_verifier().is_ok());
    }

    #[test]
    fn non_existence_verifier_loads_from_embedded_vkey() {
        assert!(non_existence_verifier().is_ok());
    }

    #[test]
    fn unified_verifier_loads_from_embedded_vkey() {
        // The unified vkey is generated by the trusted-setup ceremony and is
        // not committed; before a ceremony run `build.rs` drops a placeholder
        // stub. Only assert a real (non-placeholder) vkey parses.
        if UNIFIED_VKEY_JSON.contains("\"placeholder\"") {
            return;
        }
        assert!(unified_verifier().is_ok());
    }

    #[cfg(feature = "quorum-circuit")]
    #[test]
    fn federation_quorum_verifier_loads_or_is_placeholder() {
        // The federation_quorum vkey is ceremony-produced and not committed;
        // build.rs drops a placeholder stub pre-ceremony. Only assert a real
        // (non-placeholder) vkey parses — mirrors the unified circuit test.
        if FEDERATION_QUORUM_VKEY_JSON.contains("\"placeholder\"") {
            return;
        }
        assert!(federation_quorum_verifier().is_ok());
    }

    #[test]
    fn singleton_returns_stable_reference() {
        // Two consecutive calls must yield the same `&'static CircuitVerifier`
        // — i.e. the OnceLock cache works and we're not rebuilding on every
        // call.
        let a = existence_verifier().expect("first load");
        let b = existence_verifier().expect("second load");
        assert!(std::ptr::eq(a, b));
    }

    #[test]
    fn verify_propagates_proof_parse_errors() {
        // Pass malformed proof JSON to verify() — it must surface as
        // VerifyError::Proof, not silently succeed.
        let v = existence_verifier().expect("vkey loads");
        let r = v.verify("not json", &[]);
        assert!(matches!(r, Err(VerifyError::Proof(_))));
    }

    #[test]
    fn verify_proof_rejects_default_proof_for_zero_signals() {
        // A syntactically valid but bogus Groth16 proof must not be accepted.
        // This makes the real pairing result observable and kills mutants that
        // replace `verify_proof` with `Ok(true)` or `Ok(false)`.
        let v = existence_verifier().expect("vkey loads");
        let proof = ark_groth16::Proof::<Bn254>::default();
        let signals = [Fr::from(0u64), Fr::from(0u64), Fr::from(0u64)];
        assert!(matches!(v.verify_proof(&proof, &signals), Ok(false)));
    }
}
