"""
Thin wrapper around the Rust ``olympus_matcher`` extension module.

This module provides a lazy-initialised default :class:`Matcher` instance
pre-loaded with Olympus built-in patterns.  Any FastAPI route that previously
called ``re.match`` / ``re.search`` on request-supplied (untrusted) input
should import :func:`get_default_matcher` instead.

The underlying ``regex`` crate uses a DFA/NFA hybrid that runs in guaranteed
linear time — immune to catastrophic backtracking (ReDoS) by design.

Build the extension first::

    cd verifiers/rust/olympus-matcher
    maturin develop --release

Example usage::

    from app.utils.pattern_matcher import get_default_matcher

    matcher = get_default_matcher()
    result = matcher.match_first(user_supplied_text)
    if result:
        print(f"Pattern '{result.pattern}' matched at {result.span}")

Regex call-site audit
~~~~~~~~~~~~~~~~~~~~~

The following ``re.*`` call sites exist in the codebase.  Each was reviewed
for ReDoS exposure on untrusted input.

**Safe — trusted / internal input only (no action required):**

- ``alembic/env.py`` — ``re.sub`` on the ``DATABASE_URL`` environment
  variable.  Server-controlled config; not attacker-supplied.
- ``validate_db_config.py`` — ``re.findall`` on the local
  ``docker-compose.yml`` file.  Developer tooling; not exposed at runtime.
- ``tests/test_docker_compose_db_init.py`` — ``re.search`` on fixture
  strings.  Test-only code; never reaches production.
- ``tests/chaos/test_clock_skew.py`` — ``re.compile`` / ``re.match`` on
  timestamps generated by the system under test.  Test-only code.

**Operates on untrusted document content (low risk, simple patterns):**

- ``protocol/canonicalizer.py:144`` — ``re.sub(r"\\s+", "", attr_value)``
  on HTML attribute values from ingested documents.  The pattern ``\\s+`` is
  a single character-class repeat — guaranteed O(n) in all engines.
- ``protocol/canonicalizer.py:228-232`` — ``re.sub`` for scientific-number
  formatting.  Operates on ``format(d, "e")`` output (Python-generated
  string), not raw untrusted bytes.
- ``protocol/canonicalizer.py:368-370`` — ``re.sub(r"\\s+", " ", ...)``
  on HTML element text/tail.  Same O(n) single character-class pattern;
  input size is already bounded by ``MAX_HTML_BYTES`` (50 MiB).

None of the current ``re.*`` call sites use patterns vulnerable to
catastrophic backtracking.  The simple ``\\s+`` and literal patterns are all
O(n) even in Python's PCRE engine.  However, any **future** regex on
request-supplied input should use :func:`get_default_matcher` (backed by
the Rust ``regex`` crate DFA) instead of ``re.*`` to preserve the
linear-time guarantee.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from olympus_matcher import Matcher, MatchResult  # noqa: F401

_DEFAULT_MATCHER: "Matcher | None" = None


def get_default_matcher() -> "Matcher":
    """Return the lazily-initialised default :class:`Matcher`.

    The matcher is created once and reused for the lifetime of the process.
    Built-in Olympus patterns are registered on first access.

    Returns:
        A :class:`~olympus_matcher.Matcher` loaded with the built-in patterns.

    Raises:
        ImportError: if the ``olympus_matcher`` Rust extension has not been
            compiled and installed (run ``maturin develop --release``).
    """
    global _DEFAULT_MATCHER
    if _DEFAULT_MATCHER is None:
        from olympus_matcher import Matcher  # type: ignore[import]

        m = Matcher()
        # ── Built-in Olympus patterns ────────────────────────────────────────
        # Redaction marker: matches the literal token [REDACTED] in documents.
        m.add_pattern("redaction_marker", '"[REDACTED]"')
        # Document file references: PDF and DOCX attachments.
        m.add_pattern("doc_reference", "*.pdf|*.docx")
        # ────────────────────────────────────────────────────────────────────
        _DEFAULT_MATCHER = m
    return _DEFAULT_MATCHER
