"""
Merkle tree implementation for Olympus

This module implements Merkle trees and Merkle forests for efficient
cryptographic commitments and proof generation.
"""

import logging
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Optional

from .events import CanonicalEvent
from .hashes import HASH_SEPARATOR, LEAF_PREFIX, blake3_hash, node_hash


# Merkle tree version - DO NOT CHANGE
# Changing this breaks all historical Merkle proofs
MERKLE_VERSION = "merkle_v1"

# Proof format version.  Increment when the proof schema changes in a
# backward-incompatible way.  Old proofs carry the version they were
# produced with so verifiers can apply the correct algorithm.
PROOF_VERSION = "proof_v1"

_SEP = HASH_SEPARATOR.encode("utf-8")
logger = logging.getLogger(__name__)


@dataclass
class MerkleNode:
    """A node in a Merkle tree."""

    hash: bytes
    left: Optional["MerkleNode"] = None
    right: Optional["MerkleNode"] = None


@dataclass
class MerkleProof:
    """A Merkle inclusion proof.

    Versioning fields
    -----------------
    proof_version : str
        Version of the proof schema (default: ``PROOF_VERSION``).  Verifiers
        should reject proofs whose ``proof_version`` they do not recognise.
    tree_version : str
        Version of the Merkle tree construction algorithm (default:
        ``MERKLE_VERSION``).  Changing the tree algorithm requires a new
        ``tree_version`` so that proofs generated by different versions can
        be distinguished.
    epoch : int
        Logical epoch counter at proof generation time (default 0).  Use this
        to tie a proof to a specific ledger epoch so that epoch-scoped key
        rotation or registry changes can be detected.
    tree_size : int
        Number of leaves in the tree at the time the proof was generated.
        Required so verifiers can detect proofs from trees of different sizes
        being presented against the same root.
    """

    leaf_hash: bytes
    leaf_index: int
    # sibling positions stored as canonical "left"/"right" strings; __post_init__
    # normalizes legacy boolean inputs where encountered.
    siblings: Sequence[tuple[bytes, str | bool]]
    root_hash: bytes
    proof_version: str = PROOF_VERSION
    tree_version: str = MERKLE_VERSION
    epoch: int = 0
    tree_size: int = 0

    def __post_init__(self) -> None:
        """Normalize sibling positions to canonical 'left'/'right' strings."""
        normalized: list[tuple[bytes, str]] = []
        for sibling_hash, position in self.siblings:
            if isinstance(position, bool):
                position = "right" if position else "left"
            if position not in ("left", "right"):
                raise ValueError("Sibling position must be 'left' or 'right'")
            normalized.append((sibling_hash, position))
        # Use object.__setattr__ to update the field during initialization while keeping
        # runtime instances immutable and canonical (always string positions).
        object.__setattr__(self, "siblings", normalized)


@dataclass
class InclusionProof(MerkleProof):
    """Alias for MerkleProof to match protocol terminology."""


class MerkleTree:
    """
    A Merkle tree for committing to a set of documents.
    """

    def __init__(self, leaves: Sequence[bytes | CanonicalEvent]):
        """
        Construct a Merkle tree from leaf data.

        Leaf data is domain-separated using LEAF_PREFIX before tree construction,
        ensuring structural ambiguity between leaf nodes and internal nodes is
        impossible (second-preimage resistance).

        Args:
            leaves: List of leaf data (canonical event bytes or CanonicalEvent instances)
        """
        if not leaves:
            raise ValueError("Cannot create empty Merkle tree")

        self.leaves: list[bytes] = [self._extract_leaf_bytes(leaf) for leaf in leaves]
        # Apply LEAF_PREFIX domain separation with HASH_SEPARATOR to prevent
        # collisions with internal nodes and to follow structured hashing rules.
        self._leaf_hashes: list[bytes] = [merkle_leaf_hash(leaf) for leaf in self.leaves]
        leaf_nodes = [MerkleNode(hash=h) for h in self._leaf_hashes]
        self._root_node = self._build_tree(leaf_nodes)

    @staticmethod
    def _extract_leaf_bytes(leaf: bytes | CanonicalEvent) -> bytes:
        """Normalize leaf input to raw bytes."""
        if isinstance(leaf, CanonicalEvent):
            return leaf.canonical_bytes
        if isinstance(leaf, bytes | bytearray):
            return bytes(leaf)
        raise ValueError("Leaves must be bytes or CanonicalEvent instances")

    def _build_tree(self, nodes: list[MerkleNode]) -> MerkleNode:
        """Build tree from bottom up."""
        if len(nodes) == 1:
            return nodes[0]

        # Build parent level
        parents = []
        for i in range(0, len(nodes), 2):
            left_node = nodes[i]
            right_node = nodes[i + 1] if i + 1 < len(nodes) else nodes[i]
            parent_hash = node_hash(left_node.hash, right_node.hash)
            parents.append(
                MerkleNode(
                    hash=parent_hash,
                    left=left_node,
                    right=right_node,
                )
            )

        return self._build_tree(parents)

    def get_root(self) -> bytes:
        """Get the Merkle root hash."""
        return self._root_node.hash

    def root(self) -> bytes:
        """Get the Merkle root hash (alias for get_root)."""
        return self.get_root()

    def generate_proof(self, leaf_index: int, epoch: int = 0) -> MerkleProof:
        """
        Generate inclusion proof for a leaf.

        Args:
            leaf_index: Index of leaf to prove
            epoch: Logical ledger epoch at proof generation time.  Pass the
                current epoch from the enclosing ledger/shard context so that
                proofs can be tied to a specific epoch for key-rotation and
                registry-change detection.  Defaults to 0 when epoch tracking
                is not required at this layer.

        Returns:
            Merkle proof
        """
        if leaf_index < 0 or leaf_index >= len(self.leaves):
            raise ValueError("Invalid leaf index")

        leaf_hash = self._leaf_hashes[leaf_index]
        siblings: list[tuple[bytes, str]] = []

        # Collect siblings along path to root
        current_level: list[MerkleNode] = [MerkleNode(hash=h) for h in self._leaf_hashes]
        index = leaf_index

        while len(current_level) > 1:
            if index % 2 == 0:
                # Left child, sibling is on right
                sibling_index = index + 1 if index + 1 < len(current_level) else index
                siblings.append((current_level[sibling_index].hash, "right"))
            else:
                # Right child, sibling is on left
                siblings.append((current_level[index - 1].hash, "left"))

            # Move to parent level
            new_level: list[MerkleNode] = []
            for i in range(0, len(current_level), 2):
                left = current_level[i]
                right = current_level[i + 1] if i + 1 < len(current_level) else current_level[i]
                new_hash = node_hash(left.hash, right.hash)
                new_level.append(MerkleNode(hash=new_hash, left=left, right=right))

            current_level = new_level
            index = index // 2

        return MerkleProof(
            leaf_hash=leaf_hash,
            leaf_index=leaf_index,
            siblings=siblings,
            root_hash=self._root_node.hash,
            proof_version=PROOF_VERSION,
            tree_version=MERKLE_VERSION,
            epoch=epoch,
            tree_size=len(self.leaves),
        )


def verify_proof(proof: MerkleProof) -> bool:
    """
    Verify a Merkle inclusion proof with strict depth and position checks.

    This function enforces:
    1. Exact proof depth based on tree_size (rejects proofs that are too short or too long)
    2. Canonical sibling position representation (only "left" or "right" strings, rejects booleans)
    3. Valid tree_size (must be positive for strict verification)
    4. Valid leaf_index (must be within tree bounds when tree_size is known)

    For legacy proofs where tree_size=0 (indicating unknown tree size), the function
    performs basic verification without depth checks. However, new proofs must always
    include tree_size for strict verification.

    Args:
        proof: Merkle proof to verify

    Returns:
        True if proof is valid, False otherwise

    Raises:
        ValueError: If proof structure is malformed (invalid positions, incorrect depth, etc.)
    """
    # Strict validation: all sibling positions must be canonical strings ("left" or "right")
    # Reject boolean positions - they must be normalized before verification
    for i, (sibling_hash, position) in enumerate(proof.siblings):
        if isinstance(position, bool):
            raise ValueError(
                f"Invalid sibling position at index {i}: got boolean {position}, "
                f"expected canonical string 'left' or 'right'. "
                f"Positions must be normalized before verification."
            )
        if position not in ("left", "right"):
            raise ValueError(
                f"Invalid sibling position at index {i}: '{position}' "
                f"(must be exactly 'left' or 'right')"
            )

    # Strict depth validation (only for proofs with known tree_size)
    if proof.tree_size > 0:
        # Strict validation: leaf_index must be within bounds
        if proof.leaf_index < 0 or proof.leaf_index >= proof.tree_size:
            raise ValueError(
                f"Invalid leaf_index: {proof.leaf_index} (must be in range [0, {proof.tree_size}))"
            )

        # Calculate expected proof depth from tree_size
        # For a tree with n leaves, depth = ceil(log2(n)) for n > 1, else 0
        if proof.tree_size == 1:
            expected_depth = 0
        else:
            expected_depth = (proof.tree_size - 1).bit_length()

        # Strict validation: proof must have exactly the expected number of siblings
        actual_depth = len(proof.siblings)
        if actual_depth != expected_depth:
            raise ValueError(
                f"Invalid proof depth: expected {expected_depth} siblings for tree_size={proof.tree_size}, "
                f"got {actual_depth}"
            )

    # Compute the root hash by walking up the tree
    current_hash = proof.leaf_hash

    for sibling_hash, position in proof.siblings:
        if position == "right":
            current_hash = node_hash(current_hash, sibling_hash)
        else:  # position == "left"
            current_hash = node_hash(sibling_hash, current_hash)

    return current_hash == proof.root_hash


def _largest_power_of_two_less_than(n: int) -> int:
    """Return the largest power of two strictly less than ``n``."""
    if n <= 1:
        return 1
    return 1 << ((n - 1).bit_length() - 1)


def _subtree_root(leaf_hashes: Sequence[bytes], start: int, size: int) -> bytes:
    """Compute the Merkle root for a contiguous slice of leaves."""
    if size <= 0:
        raise ValueError("Subtree size must be positive")
    end = start + size
    if end > len(leaf_hashes):
        raise ValueError("Subtree range exceeds available leaves")
    return ct_merkle_root(list(leaf_hashes[start:end]))


def ct_merkle_root(leaves: Sequence[bytes]) -> bytes:
    """
    Compute a Merkle root without duplicating the last leaf (CT-style).

    Args:
        leaves: List of leaf hashes.

    Returns:
        Root hash of the Merkle tree.
    """
    if not leaves:
        raise ValueError("Cannot compute Merkle root of empty list")

    level = list(leaves)
    while len(level) > 1:
        next_level: list[bytes] = []
        for i in range(0, len(level), 2):
            if i + 1 < len(level):
                next_level.append(node_hash(level[i], level[i + 1]))
            else:
                next_level.append(level[i])
        level = next_level
    return level[0]


def generate_consistency_proof(
    leaf_hashes: Sequence[bytes], old_size: int, new_size: int
) -> list[bytes]:
    """
    Generate a Merkle consistency proof demonstrating that a tree of ``new_size``
    leaves extends a prior tree of ``old_size`` leaves.

    This proof contains the ordered leaf hashes for the newer tree. The verifier
    recomputes both the previous root (over the first ``old_size`` leaves) and
    the current root (over all ``new_size`` leaves) to confirm append-only growth.

    Args:
        leaf_hashes: Pre-hashed Merkle leaves (32-byte hashes).
        old_size: Number of leaves in the prior tree.
        new_size: Number of leaves in the current tree (must satisfy new_size >= old_size).

    Returns:
        List of subtree hashes (bytes) forming the consistency proof.

    Raises:
        ValueError: If sizes are invalid or leaf_hashes are insufficient.
    """
    if old_size < 0 or new_size < 0:
        raise ValueError("Tree sizes must be non-negative")
    if old_size > new_size:
        raise ValueError("old_size cannot exceed new_size")
    if new_size > len(leaf_hashes):
        raise ValueError("Not enough leaf hashes to build the requested tree")
    if old_size == 0 or old_size == new_size:
        return list(leaf_hashes[:new_size])

    return list(leaf_hashes[:new_size])


def verify_consistency_proof(
    old_root: bytes,
    new_root: bytes,
    proof: Sequence[bytes],
    old_size: int,
    new_size: int,
) -> bool:
    """
    Verify that ``new_root`` represents a Merkle tree that extends the tree with
    root ``old_root``.

    Args:
        old_root: Merkle root of the prior tree (size ``old_size``).
        new_root: Merkle root of the newer tree (size ``new_size``).
        proof: Consistency proof as produced by :func:`generate_consistency_proof`.
        old_size: Leaf count of the prior tree.
        new_size: Leaf count of the newer tree (must satisfy new_size >= old_size).

    Returns:
        True if the proof is valid and demonstrates append-only growth.
    """
    if old_size < 0 or new_size < 0 or old_size > new_size:
        return False
    if old_size == 0:
        return True
    if not proof or len(proof) < new_size:
        return False

    try:
        computed_old_root = ct_merkle_root(list(proof[:old_size]))
        computed_new_root = ct_merkle_root(list(proof[:new_size]))
    except ValueError:
        return False

    return computed_old_root == old_root and computed_new_root == new_root


def deserialize_merkle_proof(proof_data: dict[str, Any]) -> MerkleProof:
    """
    Deserialize a Merkle proof, normalizing legacy sibling encodings.

    Historical serialized proofs used string values ("left"/"right") for sibling
    positions. Modern proofs use booleans. This function accepts both and
    normalizes them to the canonical string form before constructing a MerkleProof.

    Versioning fields (``proof_version``, ``tree_version``, ``epoch``,
    ``tree_size``) are read from the serialized data when present so that old
    proofs produced without those fields round-trip correctly using the defaults
    defined on :class:`MerkleProof`.

    Args:
        proof_data: Serialized Merkle proof dictionary.

    Returns:
        MerkleProof with normalized sibling positions.
    """
    normalized_siblings: list[tuple[bytes, str]] = []
    for sibling_hash_hex, is_right in proof_data.get("siblings", []):
        if isinstance(is_right, str):
            normalized_flag = is_right.lower() == "right"
            logger.debug("Normalized legacy sibling format", extra={"is_right": is_right})
        else:
            normalized_flag = bool(is_right)
        normalized_siblings.append(
            (bytes.fromhex(sibling_hash_hex), "right" if normalized_flag else "left")
        )

    try:
        epoch_val = int(proof_data.get("epoch", 0))
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Malformed proof: 'epoch' must be an integer, got {proof_data.get('epoch')!r}"
        ) from exc
    try:
        tree_size_val = int(proof_data.get("tree_size", 0))
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Malformed proof: 'tree_size' must be an integer, got {proof_data.get('tree_size')!r}"
        ) from exc

    return MerkleProof(
        leaf_hash=bytes.fromhex(str(proof_data["leaf_hash"])),
        leaf_index=int(proof_data["leaf_index"]),
        siblings=normalized_siblings,
        root_hash=bytes.fromhex(str(proof_data["root_hash"])),
        proof_version=str(proof_data.get("proof_version", PROOF_VERSION)),
        tree_version=str(proof_data.get("tree_version", MERKLE_VERSION)),
        epoch=epoch_val,
        tree_size=tree_size_val,
    )


def merkle_leaf_hash(payload: bytes) -> bytes:
    """
    Compute the domain-separated hash of a leaf payload using HASH_SEPARATOR.

    Args:
        payload: Raw leaf payload (canonical event bytes).

    Returns:
        32-byte BLAKE3 hash for use as a Merkle leaf.
    """
    if not isinstance(payload, bytes | bytearray):
        raise ValueError("Leaf payload must be bytes")
    return blake3_hash([LEAF_PREFIX, _SEP, bytes(payload)])
