"""
Merkle tree implementation for Olympus

This module implements Merkle trees and Merkle forests for efficient
cryptographic commitments and proof generation.
"""

import logging
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Optional

from .events import CanonicalEvent
from .hashes import HASH_SEPARATOR, LEAF_PREFIX, blake3_hash, node_hash


# Merkle tree version - DO NOT CHANGE
# Changing this breaks all historical Merkle proofs
MERKLE_VERSION = "merkle_v1"

# Proof format version.  Increment when the proof schema changes in a
# backward-incompatible way.  Old proofs carry the version they were
# produced with so verifiers can apply the correct algorithm.
PROOF_VERSION = "proof_v1"

# Whitelist of recognized proof versions (L3-C)
SUPPORTED_PROOF_VERSIONS: frozenset[str] = frozenset({"proof_v1"})

# L5-D: Maximum allowed proof depth to prevent algorithmic complexity DoS.
# For sparse Merkle trees, 256 is the maximum (256-bit key space).
# For standard Merkle trees, this is still a generous limit (2^256 leaves).
MAX_PROOF_DEPTH = 256

# Canonical empty-tree commitment.  This is the root hash of a tree with
# zero leaves and MUST be used as the only valid ``old_root`` when
# ``old_size=0`` in consistency proof verification.
EMPTY_TREE_HASH = blake3_hash([b"OLY:EMPTY-TREE:V1"])

_SEP = HASH_SEPARATOR.encode("utf-8")
logger = logging.getLogger(__name__)


@dataclass
class MerkleNode:
    """A node in a Merkle tree."""

    hash: bytes
    left: Optional["MerkleNode"] = None
    right: Optional["MerkleNode"] = None


@dataclass
class MerkleProof:
    """A Merkle inclusion proof.

    Versioning fields
    -----------------
    proof_version : str
        Version of the proof schema (default: ``PROOF_VERSION``).  Verifiers
        should reject proofs whose ``proof_version`` they do not recognise.
    tree_version : str
        Version of the Merkle tree construction algorithm (default:
        ``MERKLE_VERSION``).  Changing the tree algorithm requires a new
        ``tree_version`` so that proofs generated by different versions can
        be distinguished.
    epoch : int
        Logical epoch counter at proof generation time (default 0).  Use this
        to tie a proof to a specific ledger epoch so that epoch-scoped key
        rotation or registry changes can be detected.
    tree_size : int
        Number of leaves in the tree at the time the proof was generated.
        Required so verifiers can detect proofs from trees of different sizes
        being presented against the same root.
    """

    leaf_hash: bytes
    leaf_index: int
    # sibling positions stored as canonical "left"/"right" strings; __post_init__
    # normalizes legacy boolean inputs where encountered.
    siblings: Sequence[tuple[bytes, str | bool]]
    root_hash: bytes
    proof_version: str = PROOF_VERSION
    tree_version: str = MERKLE_VERSION
    epoch: int = 0
    tree_size: int = 0

    def __post_init__(self) -> None:
        """Normalize sibling positions to canonical 'left'/'right' strings."""
        normalized: list[tuple[bytes, str]] = []
        for sibling_hash, position in self.siblings:
            if isinstance(position, bool):
                position = "right" if position else "left"
            if position not in ("left", "right"):
                raise ValueError("Sibling position must be 'left' or 'right'")
            normalized.append((sibling_hash, position))
        # Use object.__setattr__ to update the field during initialization while keeping
        # runtime instances immutable and canonical (always string positions).
        object.__setattr__(self, "siblings", normalized)


@dataclass
class InclusionProof(MerkleProof):
    """Alias for MerkleProof to match protocol terminology."""


class MerkleTree:
    """
    A Merkle tree for committing to a set of documents.
    """

    def __init__(self, leaves: Sequence[bytes | CanonicalEvent]):
        """
        Construct a Merkle tree from leaf data.

        Leaf data is domain-separated using LEAF_PREFIX before tree construction,
        ensuring structural ambiguity between leaf nodes and internal nodes is
        impossible (second-preimage resistance).

        Args:
            leaves: List of leaf data (canonical event bytes or CanonicalEvent instances)
        """
        if not leaves:
            raise ValueError("Cannot create empty Merkle tree")

        self.leaves: list[bytes] = [self._extract_leaf_bytes(leaf) for leaf in leaves]
        # Apply LEAF_PREFIX domain separation with HASH_SEPARATOR to prevent
        # collisions with internal nodes and to follow structured hashing rules.
        self._leaf_hashes: list[bytes] = [merkle_leaf_hash(leaf) for leaf in self.leaves]
        leaf_nodes = [MerkleNode(hash=h) for h in self._leaf_hashes]
        self._root_node = self._build_tree(leaf_nodes)

    @staticmethod
    def _extract_leaf_bytes(leaf: bytes | CanonicalEvent) -> bytes:
        """Normalize leaf input to raw bytes."""
        if isinstance(leaf, CanonicalEvent):
            return leaf.canonical_bytes
        if isinstance(leaf, bytes | bytearray):
            return bytes(leaf)
        raise ValueError("Leaves must be bytes or CanonicalEvent instances")

    def _build_tree(self, nodes: list[MerkleNode]) -> MerkleNode:
        """Build tree from bottom up using CT-style promotion."""
        if len(nodes) == 1:
            return nodes[0]

        # Build parent level
        parents = []
        for i in range(0, len(nodes), 2):
            left_node = nodes[i]
            if i + 1 < len(nodes):
                # Pair exists: hash left and right
                right_node = nodes[i + 1]
                parent_hash = node_hash(left_node.hash, right_node.hash)
                parents.append(
                    MerkleNode(
                        hash=parent_hash,
                        left=left_node,
                        right=right_node,
                    )
                )
            else:
                # CT-style promotion: lone node is promoted without hashing
                parents.append(left_node)

        return self._build_tree(parents)

    def get_root(self) -> bytes:
        """Get the Merkle root hash."""
        return self._root_node.hash

    def root(self) -> bytes:
        """Get the Merkle root hash (alias for get_root)."""
        return self.get_root()

    def generate_proof(self, leaf_index: int, epoch: int = 0) -> MerkleProof:
        """
        Generate inclusion proof for a leaf.

        Args:
            leaf_index: Index of leaf to prove
            epoch: Logical ledger epoch at proof generation time.  Pass the
                current epoch from the enclosing ledger/shard context so that
                proofs can be tied to a specific epoch for key-rotation and
                registry-change detection.  Defaults to 0 when epoch tracking
                is not required at this layer.

        Returns:
            Merkle proof
        """
        if leaf_index < 0 or leaf_index >= len(self.leaves):
            raise ValueError("Invalid leaf index")

        leaf_hash = self._leaf_hashes[leaf_index]
        siblings: list[tuple[bytes, str]] = []

        # Collect siblings along path to root using CT-style promotion
        current_level: list[MerkleNode] = [MerkleNode(hash=h) for h in self._leaf_hashes]
        index = leaf_index

        while len(current_level) > 1:
            # Check if this index is at the promoted (odd) position
            if index == len(current_level) - 1 and len(current_level) % 2 == 1:
                # Lone node is promoted - no sibling at this level
                pass
            elif index % 2 == 0:
                # Left child, sibling is on right
                siblings.append((current_level[index + 1].hash, "right"))
            else:
                # Right child, sibling is on left
                siblings.append((current_level[index - 1].hash, "left"))

            # Move to parent level using CT-style promotion
            new_level: list[MerkleNode] = []
            for i in range(0, len(current_level), 2):
                left = current_level[i]
                if i + 1 < len(current_level):
                    right = current_level[i + 1]
                    new_hash = node_hash(left.hash, right.hash)
                    new_level.append(MerkleNode(hash=new_hash, left=left, right=right))
                else:
                    # CT-style promotion: lone node is promoted without hashing
                    new_level.append(left)

            current_level = new_level
            index = index // 2

        return MerkleProof(
            leaf_hash=leaf_hash,
            leaf_index=leaf_index,
            siblings=siblings,
            root_hash=self._root_node.hash,
            proof_version=PROOF_VERSION,
            tree_version=MERKLE_VERSION,
            epoch=epoch,
            tree_size=len(self.leaves),
        )


def verify_proof(proof: MerkleProof) -> bool:
    """
    Verify a Merkle inclusion proof with strict depth and position checks.

    This function enforces:
    1. Exact proof depth based on tree_size (rejects proofs that are too short or too long)
    2. Canonical sibling position representation (only "left" or "right" strings, rejects booleans)
    3. Valid tree_size (must be positive for strict verification)
    4. Valid leaf_index (must be within tree bounds when tree_size is known)
    5. Recognized proof_version (L3-C)

    For legacy proofs where tree_size=0 (indicating unknown tree size), the function
    performs basic verification without depth checks. However, new proofs must always
    include tree_size for strict verification.

    Args:
        proof: Merkle proof to verify

    Returns:
        True if proof is valid, False otherwise

    Raises:
        ValueError: If proof structure is malformed (invalid positions, incorrect depth,
            unknown proof_version, etc.)
    """
    # L3-C: Validate proof_version against whitelist
    if proof.proof_version not in SUPPORTED_PROOF_VERSIONS:
        raise ValueError(
            f"Unknown proof_version: '{proof.proof_version}'. "
            f"Supported versions: {sorted(SUPPORTED_PROOF_VERSIONS)}"
        )

    # Strict validation: all sibling positions must be canonical strings ("left" or "right")
    # Reject boolean positions - they should be normalized by MerkleProof.__post_init__
    # during proof construction. If we see booleans here, the proof was constructed incorrectly.
    for i, (sibling_hash, position) in enumerate(proof.siblings):
        if isinstance(position, bool):
            raise ValueError(
                f"Invalid sibling position at index {i}: got boolean {position}, "
                f"expected canonical string 'left' or 'right'. "
                f"Positions should be normalized by MerkleProof.__post_init__ during construction."
            )
        if position not in ("left", "right"):
            raise ValueError(
                f"Invalid sibling position at index {i}: '{position}' "
                f"(must be exactly 'left' or 'right')"
            )

    # Strict depth validation (only for proofs with known tree_size)
    if proof.tree_size > 0:
        # Strict validation: leaf_index must be within bounds
        if proof.leaf_index < 0 or proof.leaf_index >= proof.tree_size:
            raise ValueError(
                f"Invalid leaf_index: {proof.leaf_index} (must be in range [0, {proof.tree_size}))"
            )

        # For CT-style trees, the number of siblings depends on where the leaf
        # is in the tree. Promoted leaves have fewer siblings.
        # Maximum depth is ceil(log2(n)) for n > 1
        if proof.tree_size == 1:
            expected_max_depth = 0
        else:
            expected_max_depth = (proof.tree_size - 1).bit_length()

        actual_depth = len(proof.siblings)
        # In CT-style, proof depth can be less than max depth due to promotion
        if actual_depth > expected_max_depth:
            raise ValueError(
                f"Invalid proof depth: got {actual_depth} siblings but max expected "
                f"for tree_size={proof.tree_size} is {expected_max_depth}"
            )

    # Validate sibling positions against the leaf_index path when tree_size is known.
    # At each level k, the node's index determines whether it is a left or right child:
    #   even index → left child → sibling must be "right"
    #   odd  index → right child → sibling must be "left"
    if proof.tree_size > 0 and proof.siblings:
        index = proof.leaf_index
        level_size = proof.tree_size
        sibling_idx = 0

        while level_size > 1 and sibling_idx < len(proof.siblings):
            # Check if this node is the lone node at this level (CT-style promoted)
            is_last = index == level_size - 1
            is_promoted = is_last and (level_size % 2 == 1)

            if not is_promoted:
                # There should be a sibling at this level
                _sibling_hash, position = proof.siblings[sibling_idx]
                expected_pos = "right" if index % 2 == 0 else "left"
                if position != expected_pos:
                    return False
                sibling_idx += 1

            # Move to next level
            level_size = (level_size + 1) // 2
            index = index // 2

    # Compute the root hash by walking up the tree
    current_hash = proof.leaf_hash

    for sibling_hash, position in proof.siblings:
        if position == "right":
            current_hash = node_hash(current_hash, sibling_hash)
        else:  # position == "left"
            current_hash = node_hash(sibling_hash, current_hash)

    return current_hash == proof.root_hash


def _largest_power_of_two_less_than(n: int) -> int:
    """Return the largest power of two strictly less than ``n``."""
    if n <= 1:
        return 1
    return 1 << ((n - 1).bit_length() - 1)


def _subtree_root(leaf_hashes: Sequence[bytes], start: int, size: int) -> bytes:
    """Compute the Merkle root for a contiguous slice of leaves."""
    if size <= 0:
        raise ValueError("Subtree size must be positive")
    end = start + size
    if end > len(leaf_hashes):
        raise ValueError("Subtree range exceeds available leaves")
    return ct_merkle_root(list(leaf_hashes[start:end]))


def ct_merkle_root(leaves: Sequence[bytes]) -> bytes:
    """
    Compute a Merkle root without duplicating the last leaf (CT-style).

    Args:
        leaves: List of leaf hashes.

    Returns:
        Root hash of the Merkle tree.
    """
    if not leaves:
        raise ValueError("Cannot compute Merkle root of empty list")

    level = list(leaves)
    while len(level) > 1:
        next_level: list[bytes] = []
        for i in range(0, len(level), 2):
            if i + 1 < len(level):
                next_level.append(node_hash(level[i], level[i + 1]))
            else:
                next_level.append(level[i])
        level = next_level
    return level[0]


def generate_consistency_proof(
    leaf_hashes: Sequence[bytes], old_size: int, new_size: int
) -> list[bytes]:
    """
    Generate a Merkle consistency proof demonstrating that a tree of ``new_size``
    leaves extends a prior tree of ``old_size`` leaves.

    This implements RFC 6962 Certificate Transparency style consistency proofs.
    The proof contains a minimal set of subtree hashes (O(log n)) that allows
    the verifier to reconstruct both the old and new roots, confirming that
    the tree has grown in an append-only manner.

    Args:
        leaf_hashes: Pre-hashed Merkle leaves (32-byte hashes).
        old_size: Number of leaves in the prior tree.
        new_size: Number of leaves in the current tree (must satisfy new_size >= old_size).

    Returns:
        List of subtree hashes (bytes) forming the consistency proof.

    Raises:
        ValueError: If sizes are invalid or leaf_hashes are insufficient.
    """
    if old_size < 0 or new_size < 0:
        raise ValueError("Tree sizes must be non-negative")
    if old_size > new_size:
        raise ValueError("old_size cannot exceed new_size")
    if new_size > len(leaf_hashes):
        raise ValueError("Not enough leaf hashes to build the requested tree")

    # Trivial cases
    if old_size == 0:
        return []
    if old_size == new_size:
        return []

    # Compute RFC 6962 style consistency proof
    return _subproof_ct(leaf_hashes, old_size, new_size, True)


def _subproof_ct(
    leaf_hashes: Sequence[bytes], old_size: int, new_size: int, is_root: bool
) -> list[bytes]:
    """
    Recursive helper for RFC 6962 consistency proof generation.

    Args:
        leaf_hashes: All leaf hashes (size >= new_size)
        old_size: Size of the old tree (m in RFC 6962)
        new_size: Size of the new tree (n in RFC 6962)
        is_root: True if we're at the tree root

    Returns:
        List of subtree hashes needed for the consistency proof
    """
    # Base case: trees are identical
    if old_size == new_size:
        if is_root:
            return []
        else:
            # Not at root - need the subtree root
            return [ct_merkle_root(list(leaf_hashes[:old_size]))]

    # Find largest power of 2 less than new_size (k in RFC 6962)
    k = 1
    while k * 2 < new_size:
        k *= 2

    if old_size <= k:
        # old_size is in the left subtree
        # Need: SUBPROOF(old_size, k, False) + [right_subtree_root]
        # When we recurse into a subtree, is_root should be False
        left_proof = _subproof_ct(leaf_hashes[:k], old_size, k, False)
        if new_size > k:
            right_root = ct_merkle_root(list(leaf_hashes[k:new_size]))
            return left_proof + [right_root]
        else:
            return left_proof
    else:
        # old_size is in the right subtree (old_size > k)
        # Need: [left_subtree_root] + SUBPROOF(old_size - k, new_size - k, False)
        left_root = ct_merkle_root(list(leaf_hashes[:k]))
        right_proof = _subproof_ct(leaf_hashes[k:], old_size - k, new_size - k, False)
        return [left_root] + right_proof


def verify_consistency_proof(
    old_root: bytes,
    new_root: bytes,
    proof: Sequence[bytes],
    old_size: int,
    new_size: int,
) -> bool:
    """
    Verify that ``new_root`` represents a Merkle tree that extends the tree with
    root ``old_root``.

    This implements RFC 6962 Certificate Transparency style consistency proof
    verification. The proof contains O(log n) subtree hashes that allow
    reconstruction of both the old and new tree roots.

    Args:
        old_root: Merkle root of the prior tree (size ``old_size``).
        new_root: Merkle root of the newer tree (size ``new_size``).
        proof: Consistency proof as produced by :func:`generate_consistency_proof`.
        old_size: Leaf count of the prior tree.
        new_size: Leaf count of the newer tree (must satisfy new_size >= old_size).

    Returns:
        True if the proof is valid and demonstrates append-only growth.
    """
    if old_size < 0 or new_size < 0 or old_size > new_size:
        return False

    # Trivial cases
    if old_size == 0:
        # Empty tree is a known commitment — the root must be the canonical empty hash
        if old_root != EMPTY_TREE_HASH:
            return False
        return True  # Any new_root is consistent with an empty old tree
    if old_size == new_size:
        return old_root == new_root

    try:
        # Verify RFC 6962 consistency proof
        computed_old, computed_new, proof_consumed = _verify_subproof_ct(
            proof, 0, old_size, new_size, True
        )

        # Ensure all proof nodes were consumed
        if proof_consumed != len(proof):
            return False

        return computed_old == old_root and computed_new == new_root
    except (ValueError, IndexError):
        return False


def _verify_subproof_ct(
    proof: Sequence[bytes],
    proof_index: int,
    old_size: int,
    new_size: int,
    is_root: bool,
) -> tuple[bytes, bytes, int]:
    """
    Recursive helper for RFC 6962 consistency proof verification.

    Args:
        proof: List of subtree hashes
        proof_index: Current position in the proof
        old_size: Size of the old tree (m in RFC 6962)
        new_size: Size of the new tree (n in RFC 6962)
        is_root: True if we're at the tree root

    Returns:
        Tuple of (old_root, new_root, next_proof_index)

    Raises:
        ValueError: If proof is malformed or arguments are invalid.
    """
    # L3-D: Sanity guards for input validation
    if old_size < 0 or new_size < 0:
        raise ValueError("Tree sizes must be non-negative")
    if old_size > new_size:
        raise ValueError("old_size cannot exceed new_size in consistency proof")

    # L3-D: Handle identical-size base case before recursion
    # When old_size == new_size at the root, the proof should be empty and
    # the roots should be identical - handled in verify_consistency_proof.
    # But within recursion, identical subtrees need proof nodes.
    if old_size == new_size:
        if is_root:
            # At root with identical trees - this shouldn't happen in non-trivial cases
            # but can occur in recursive calls when a subtree is unchanged
            # We need to consume one node from the proof
            if proof_index >= len(proof):
                # No proof node available - trees must be truly identical (trivial case)
                # This shouldn't happen as trivial cases are handled in verify_consistency_proof
                raise ValueError("Proof exhausted in identical-size subtree")
            root = proof[proof_index]
            return root, root, proof_index + 1
        else:
            # Both roots are the same subtree root from proof
            if proof_index >= len(proof):
                raise ValueError("Proof exhausted prematurely")
            root = proof[proof_index]
            return root, root, proof_index + 1

    # Find largest power of 2 less than new_size (k in RFC 6962)
    k = 1
    while k * 2 < new_size:
        k *= 2

    if old_size <= k:
        # old_size is in the left subtree
        # Recurse left, then consume right root if new tree extends beyond k
        # When we recurse into a subtree, is_root should be False
        old_root_left, new_root_left, idx = _verify_subproof_ct(
            proof, proof_index, old_size, k, False
        )

        if new_size > k:
            # New tree has right subtree
            if idx >= len(proof):
                raise ValueError("Proof exhausted, expected right subtree root")
            right_root = proof[idx]
            idx += 1
            old_root = old_root_left
            new_root = node_hash(new_root_left, right_root)
        else:
            # New tree = left subtree only (new_size = k)
            old_root = old_root_left
            new_root = new_root_left

        return old_root, new_root, idx
    else:
        # old_size > k: both old and new trees have right subtrees
        # Consume left root, then recurse right
        if proof_index >= len(proof):
            raise ValueError("Proof exhausted, expected left subtree root")
        left_root = proof[proof_index]
        proof_index += 1

        old_root_right, new_root_right, idx = _verify_subproof_ct(
            proof, proof_index, old_size - k, new_size - k, False
        )

        old_root = node_hash(left_root, old_root_right)
        new_root = node_hash(left_root, new_root_right)

        return old_root, new_root, idx


def deserialize_merkle_proof(proof_data: dict[str, Any]) -> MerkleProof:
    """
    Deserialize a Merkle proof, normalizing legacy sibling encodings.

    Historical serialized proofs used string values ("left"/"right") for sibling
    positions. Modern proofs use booleans. This function accepts both and
    normalizes them to the canonical string form before constructing a MerkleProof.

    Versioning fields (``proof_version``, ``tree_version``, ``epoch``,
    ``tree_size``) are read from the serialized data when present so that old
    proofs produced without those fields round-trip correctly using the defaults
    defined on :class:`MerkleProof`.

    Args:
        proof_data: Serialized Merkle proof dictionary.

    Returns:
        MerkleProof with normalized sibling positions.

    Raises:
        ValueError: If proof_version is not in the supported whitelist or if
            other fields are malformed.
    """
    # L3-C: Validate proof_version against whitelist
    proof_version = str(proof_data.get("proof_version", PROOF_VERSION))
    if proof_version not in SUPPORTED_PROOF_VERSIONS:
        raise ValueError(
            f"Unknown proof_version: '{proof_version}'. "
            f"Supported versions: {sorted(SUPPORTED_PROOF_VERSIONS)}"
        )

    # L5-D: Validate proof depth to prevent algorithmic complexity DoS.
    # This check is performed early to reject malicious proofs before parsing
    # all sibling data.
    siblings_data = proof_data.get("siblings", [])
    if len(siblings_data) > MAX_PROOF_DEPTH:
        raise ValueError(
            f"Proof depth {len(siblings_data)} exceeds maximum allowed depth "
            f"of {MAX_PROOF_DEPTH}. This may indicate a malformed or malicious proof."
        )

    normalized_siblings: list[tuple[bytes, str]] = []
    for sibling_hash_hex, is_right in siblings_data:
        if isinstance(is_right, str):
            normalized_flag = is_right.lower() == "right"
            logger.debug("Normalized legacy sibling format", extra={"is_right": is_right})
        else:
            normalized_flag = bool(is_right)
        normalized_siblings.append(
            (bytes.fromhex(sibling_hash_hex), "right" if normalized_flag else "left")
        )

    try:
        epoch_val = int(proof_data.get("epoch", 0))
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Malformed proof: 'epoch' must be an integer, got {proof_data.get('epoch')!r}"
        ) from exc
    try:
        tree_size_val = int(proof_data.get("tree_size", 0))
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Malformed proof: 'tree_size' must be an integer, got {proof_data.get('tree_size')!r}"
        ) from exc

    return MerkleProof(
        leaf_hash=bytes.fromhex(str(proof_data["leaf_hash"])),
        leaf_index=int(proof_data["leaf_index"]),
        siblings=normalized_siblings,
        root_hash=bytes.fromhex(str(proof_data["root_hash"])),
        proof_version=proof_version,
        tree_version=str(proof_data.get("tree_version", MERKLE_VERSION)),
        epoch=epoch_val,
        tree_size=tree_size_val,
    )


def merkle_leaf_hash(payload: bytes) -> bytes:
    """
    Compute the domain-separated hash of a leaf payload using HASH_SEPARATOR.

    Args:
        payload: Raw leaf payload (canonical event bytes).

    Returns:
        32-byte BLAKE3 hash for use as a Merkle leaf.
    """
    if not isinstance(payload, bytes | bytearray):
        raise ValueError("Leaf payload must be bytes")
    return blake3_hash([LEAF_PREFIX, _SEP, bytes(payload)])
