"""
Proof System Interface (Protocol Boundary)

This module defines the strict protocol boundary for all cryptographic proof systems
in Olympus. The ProofBackendProtocol defines the contract that all proof backends
(Groth16, Halo2, Plonky2, STARKs, etc.) must implement.

Design goals:
- Strict separation between protocol logic and proving system implementation
- Zero leakage of proving system internals to the ledger layer
- Easy addition of new proof backends without protocol changes
- Auditor-friendly cryptographic modularity

Usage::

    from protocol.proof_interface import (
        ProofBackendProtocol,
        Statement,
        Witness,
        Proof,
    )

    class MyProofBackend:
        def generate(self, statement: Statement, witness: Witness) -> Proof:
            ...

        def verify(self, statement: Statement, proof: Proof) -> bool:
            ...

The protocol layer interacts with proof systems exclusively through this interface,
ensuring future backend changes do not ripple across ledger logic.
"""

from __future__ import annotations

from abc import abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Protocol, runtime_checkable


class ProofSystemType(Enum):
    """
    Enumeration of supported proof system backends.

    This enum identifies the proof system used for a given proof artifact.
    """

    GROTH16 = "groth16"
    HALO2 = "halo2"
    PLONKY2 = "plonky2"  # Reserved for future
    STARK = "stark"  # Reserved for future


@dataclass(frozen=True)
class Statement:
    """
    Public statement to be proven.

    A statement contains all public inputs and the circuit identifier.
    These values are visible to both prover and verifier.

    Attributes:
        circuit: Circuit identifier (e.g., "unified_canonicalization_inclusion_root_sign")
        public_inputs: Dictionary of public input name to value (as strings for field compatibility)
        version: Circuit version for compatibility tracking
    """

    circuit: str
    public_inputs: dict[str, str]
    version: str = "1.0.0"

    def to_list(self) -> list[str]:
        """
        Convert public inputs to ordered list format for circuit verification.

        The order is determined by sorted keys to ensure determinism.
        """
        return [self.public_inputs[k] for k in sorted(self.public_inputs.keys())]

    def to_dict(self) -> dict[str, Any]:
        """Serialize statement to dictionary."""
        return {
            "circuit": self.circuit,
            "public_inputs": self.public_inputs,
            "version": self.version,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Statement:
        """Deserialize statement from dictionary."""
        return cls(
            circuit=data["circuit"],
            public_inputs=data["public_inputs"],
            version=data.get("version", "1.0.0"),
        )


@dataclass
class Witness:
    """
    Private witness for proof generation.

    A witness contains all private inputs needed to generate a proof.
    These values are known only to the prover.

    Attributes:
        private_inputs: Dictionary of private input name to value
        auxiliary: Optional auxiliary data for proving (paths, keys, etc.)
    """

    private_inputs: dict[str, Any]
    auxiliary: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize witness to dictionary."""
        return {
            "private_inputs": self.private_inputs,
            "auxiliary": self.auxiliary,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Witness:
        """Deserialize witness from dictionary."""
        return cls(
            private_inputs=data["private_inputs"],
            auxiliary=data.get("auxiliary", {}),
        )


@dataclass
class Proof:
    """
    Cryptographic proof artifact.

    A proof encapsulates the cryptographic evidence generated by a proof backend.
    It includes metadata about the proof system used and the statement proven.

    Attributes:
        proof_data: Backend-specific proof data (Groth16 JSON, Halo2 bytes, etc.)
        proof_system: The proof system that generated this proof
        circuit: Circuit identifier
        public_signals: Public signals/inputs as list (for verification)
        metadata: Optional metadata (timing, prover version, etc.)
    """

    proof_data: dict[str, Any] | bytes
    proof_system: ProofSystemType
    circuit: str
    public_signals: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize proof to dictionary."""
        serialized_data: dict[str, Any] | str
        if isinstance(self.proof_data, bytes):
            serialized_data = self.proof_data.hex()
        else:
            serialized_data = self.proof_data
        return {
            "proof_data": serialized_data,
            "proof_system": self.proof_system.value,
            "circuit": self.circuit,
            "public_signals": self.public_signals,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Proof:
        """Deserialize proof from dictionary."""
        proof_data = data["proof_data"]
        # Handle hex-encoded bytes for Halo2 proofs
        if isinstance(proof_data, str) and data.get("proof_system") == "halo2":
            proof_data = bytes.fromhex(proof_data)
        return cls(
            proof_data=proof_data,
            proof_system=ProofSystemType(data["proof_system"]),
            circuit=data["circuit"],
            public_signals=data.get("public_signals", []),
            metadata=data.get("metadata", {}),
        )


@runtime_checkable
class ProofBackendProtocol(Protocol):
    """
    Protocol defining the contract for all proof system backends.

    This is the strict boundary between the Olympus protocol layer and any
    cryptographic proving system. Implementations must provide:

    1. generate() - Generate a proof from statement and witness
    2. verify() - Verify a proof against a statement

    All protocol-layer code interacts with proof systems exclusively through
    this interface. This ensures:

    - Future proof system changes do not ripple across ledger logic
    - New backends (Plonky2, STARKs, etc.) can be added without protocol changes
    - Clear audit boundary for cryptographic components

    Example implementation::

        class Groth16Backend:
            def generate(self, statement: Statement, witness: Witness) -> Proof:
                # Generate Groth16 proof using snarkjs
                ...

            def verify(self, statement: Statement, proof: Proof) -> bool:
                # Verify Groth16 proof using snarkjs
                ...
    """

    @abstractmethod
    def generate(self, statement: Statement, witness: Witness) -> Proof:
        """
        Generate a cryptographic proof.

        Args:
            statement: The public statement to prove (circuit + public inputs)
            witness: The private witness (private inputs + auxiliary data)

        Returns:
            Proof: A cryptographic proof that can be verified

        Raises:
            ValueError: If statement or witness is invalid
            RuntimeError: If proof generation fails
        """
        ...

    @abstractmethod
    def verify(self, statement: Statement, proof: Proof) -> bool:
        """
        Verify a cryptographic proof.

        Args:
            statement: The public statement that was proven
            proof: The cryptographic proof to verify

        Returns:
            bool: True if the proof is valid, False otherwise

        Raises:
            ValueError: If statement or proof is malformed
        """
        ...

    @property
    @abstractmethod
    def proof_system_type(self) -> ProofSystemType:
        """Return the type of proof system this backend implements."""
        ...

    @abstractmethod
    def is_available(self) -> bool:
        """
        Check if this proof backend is available and ready to use.

        Returns:
            bool: True if backend dependencies are available
        """
        ...


class ProofBackendError(Exception):
    """Base exception for proof backend errors."""

    pass


class ProofGenerationError(ProofBackendError):
    """Raised when proof generation fails."""

    pass


class ProofVerificationError(ProofBackendError):
    """Raised when proof verification fails unexpectedly."""

    pass


class BackendNotAvailableError(ProofBackendError):
    """Raised when a required proof backend is not available."""

    pass
