"""initial_foia_schema

Revision ID: 150ed68bf7cc
Revises:
Create Date: 2026-03-17 20:48:15.230027

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '150ed68bf7cc'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Enum('MUNICIPAL', 'COUNTY', 'STATE', 'FEDERAL', name='agency_level'), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('avg_response_days', sa.Float(), nullable=True),
    sa.Column('compliance_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holder_key', sa.String(length=512), nullable=False),
    sa.Column('credential_type', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('issuer', sa.String(length=256), nullable=False),
    sa.Column('sbt_nontransferable', sa.Boolean(), nullable=False),
    sa.Column('commit_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merkle_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shard_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('left_child_id', sa.String(length=36), nullable=True),
    sa.Column('right_child_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['left_child_id'], ['merkle_nodes.id'], ),
    sa.ForeignKeyConstraint(['right_child_id'], ['merkle_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_nodes_shard_id'), 'merkle_nodes', ['shard_id'], unique=False)
    op.create_table('public_records_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_id', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=True),
    sa.Column('request_type', sa.Enum('NC_PUBLIC_RECORDS', 'FEDERAL_FOIA', 'FERPA', name='request_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'IN_REVIEW', 'FULFILLED', 'DENIED', 'OVERDUE', 'APPEALED', name='request_status'), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('response_format', sa.String(length=128), nullable=False),
    sa.Column('fee_waiver_basis', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('STANDARD', 'EXPEDITED_SAFETY', 'EXPEDITED_PUBLIC_INTEREST', name='request_priority'), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('shard_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('grounds', sa.Enum('NO_RESPONSE', 'IMPROPER_EXEMPTION', 'PARTIAL_RESPONSE', 'EXCESSIVE_FEE', 'BAD_FAITH', name='appeal_grounds'), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNDER_REVIEW', 'UPHELD', 'OVERTURNED', 'DENIED_ON_APPEAL', name='appeal_status'), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['public_records_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.Column('commit_id', sa.String(length=64), nullable=False),
    sa.Column('epoch_timestamp', sa.DateTime(), nullable=False),
    sa.Column('shard_id', sa.String(length=32), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=True),
    sa.Column('zk_proof', sa.Text(), nullable=True),
    sa.Column('embargo_until', sa.DateTime(), nullable=True),
    sa.Column('is_multi_recipient', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['public_records_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_commits')
    op.drop_table('appeals')
    op.drop_table('public_records_requests')
    op.drop_index(op.f('ix_merkle_nodes_shard_id'), table_name='merkle_nodes')
    op.drop_table('merkle_nodes')
    op.drop_table('key_credentials')
    op.drop_table('agencies')
    # ### end Alembic commands ###
