//! Emit cross-language parity vectors for the Python SDK.
//!
//!   cargo run -p olympus-manifest --example gen_python_vectors > \
//!       clients/python/tests/vectors.json
//!
//! The output pins (a) the domain-separated hashing primitives the Python SDK
//! re-implements, and (b) a sealed manifest's `manifest_root` plus a real
//! inclusion and exclusion proof bundle. The Python parity test recomputes the
//! primitives and verifies the bundles against `manifest_root`, so any drift
//! between the Rust source of truth and the Python port fails the test.

use olympus_crypto::smt::{empty_subtree_hash, shard_record_key};
use olympus_crypto::{leaf_hash, node_hash, record_key};
use olympus_manifest::commit::seal;
use olympus_manifest::{DatasetMetadata, RecordEntry, RecordIndex, ShardRecords};
use serde_json::json;

fn hexs(b: &[u8]) -> String {
    hex::encode(b)
}

fn main() {
    // ── primitive vectors ─────────────────────────────────────────────────────
    let rk = record_key("olympus.dataset-record", "rec-1", 1);
    let tree_key = shard_record_key("alpha", &rk);
    let value = [0x11u8; 32];
    let lh = leaf_hash(
        b"alpha",
        &tree_key,
        &value,
        b"olympus.manifest@v1",
        b"v1",
        b"none",
    );
    let primitives = json!({
        "empty_leaf": hexs(&empty_subtree_hash(0)),
        "empty_subtree_192": hexs(&empty_subtree_hash(192)),
        "empty_subtree_256": hexs(&empty_subtree_hash(256)),
        "record_key": {
            "record_type": "olympus.dataset-record",
            "record_id": "rec-1",
            "version": 1,
            "out": hexs(&rk),
        },
        "shard_record_key": {
            "shard_id": "alpha",
            "record_key": hexs(&rk),
            "out": hexs(&tree_key),
        },
        "leaf_hash": {
            "shard_id": "alpha",
            "key": hexs(&tree_key),
            "value_hash": hexs(&value),
            "parser_id": "olympus.manifest@v1",
            "canonical_parser_version": "v1",
            "model_hash": "none",
            "out": hexs(&lh),
        },
        "node_hash": {
            "left": hexs(&[0x01u8; 32]),
            "right": hexs(&[0x02u8; 32]),
            "out": hexs(&node_hash(&[0x01u8; 32], &[0x02u8; 32])),
        },
    });

    // ── a sealed manifest + real proof bundles ────────────────────────────────
    let index = RecordIndex {
        shards: vec![
            ShardRecords {
                shard_id: "alpha".into(),
                records: vec![
                    RecordEntry {
                        record_id: "a-1".into(),
                        content_hash: "11".repeat(32),
                        version: 1,
                        byte_size: Some(10),
                    },
                    RecordEntry {
                        record_id: "a-2".into(),
                        content_hash: "22".repeat(32),
                        version: 1,
                        byte_size: Some(20),
                    },
                ],
            },
            ShardRecords {
                shard_id: "beta".into(),
                records: vec![RecordEntry {
                    record_id: "b-1".into(),
                    content_hash: "33".repeat(32),
                    version: 1,
                    byte_size: None,
                }],
            },
        ],
    };
    let sealed = seal("demo", 1, 1_700_000_000, DatasetMetadata::default(), &index).unwrap();
    let inclusion = sealed.prove_inclusion("alpha", "a-1", 1).unwrap();
    let exclusion = sealed.prove_exclusion("alpha", "ghost", 1).unwrap();

    let out = json!({
        "_comment": "Generated by `cargo run -p olympus-manifest --example gen_python_vectors`. Do not edit by hand.",
        "primitives": primitives,
        "manifest": serde_json::from_slice::<serde_json::Value>(
            &sealed.manifest.to_canonical_bytes().unwrap()
        ).unwrap(),
        "manifest_root": sealed.manifest.manifest_root,
        "inclusion_bundle": inclusion,
        "exclusion_bundle": exclusion,
    });
    println!("{}", serde_json::to_string_pretty(&out).unwrap());
}
