"""Cross-language parity: the Python port must match the Rust source of truth.

``vectors.json`` is generated by
``cargo run -p olympus-manifest --example gen_python_vectors``. These tests
recompute the domain primitives and verify real proof bundles against the
committed ``manifest_root``, so any drift between Rust and Python fails here.
"""

import json
import pathlib

import pytest

from olympus_manifest import hashing, verify, verify_against_manifest
from olympus_manifest.proof import Verdict

VECTORS = json.loads((pathlib.Path(__file__).parent / "vectors.json").read_text())


def test_primitive_parity():
    p = VECTORS["primitives"]
    assert hashing.empty_leaf().hex() == p["empty_leaf"]
    assert hashing.empty_subtree_hash(192).hex() == p["empty_subtree_192"]
    assert hashing.empty_subtree_hash(256).hex() == p["empty_subtree_256"]

    rk = p["record_key"]
    assert (
        hashing.record_key(rk["record_type"], rk["record_id"], rk["version"]).hex()
        == rk["out"]
    )

    srk = p["shard_record_key"]
    assert (
        hashing.shard_record_key(
            srk["shard_id"], bytes.fromhex(srk["record_key"])
        ).hex()
        == srk["out"]
    )

    lh = p["leaf_hash"]
    assert (
        hashing.leaf_hash(
            lh["shard_id"].encode(),
            bytes.fromhex(lh["key"]),
            bytes.fromhex(lh["value_hash"]),
            lh["parser_id"].encode(),
            lh["canonical_parser_version"].encode(),
            lh["model_hash"].encode(),
        ).hex()
        == lh["out"]
    )

    nh = p["node_hash"]
    assert (
        hashing.node_hash(bytes.fromhex(nh["left"]), bytes.fromhex(nh["right"])).hex()
        == nh["out"]
    )


def test_inclusion_bundle_verifies():
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(VECTORS["inclusion_bundle"], root) is Verdict.VALID


def test_exclusion_bundle_verifies():
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(VECTORS["exclusion_bundle"], root) is Verdict.VALID


def test_manifest_root_matches_embedded_manifest():
    assert VECTORS["manifest"]["manifest_root"] == VECTORS["manifest_root"]


def test_wrong_root_rejected():
    assert verify(VECTORS["inclusion_bundle"], b"\x00" * 32) is Verdict.ROOT_MISMATCH


def test_relabeled_record_rejected():
    bundle = json.loads(json.dumps(VECTORS["inclusion_bundle"]))
    bundle["record_id"] = "a-2"  # valid proof for a-1, relabelled
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(bundle, root) is Verdict.KEY_MISMATCH


def test_tampered_content_rejected():
    bundle = json.loads(json.dumps(VECTORS["inclusion_bundle"]))
    bundle["content_hash"] = "99" * 32
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(bundle, root) is Verdict.CONTENT_MISMATCH


def test_mismatched_kind_rejected():
    bundle = json.loads(json.dumps(VECTORS["inclusion_bundle"]))
    bundle["kind"] = "exclusion"  # existence proof labelled exclusion
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(bundle, root) is Verdict.KIND_MISMATCH


def test_tampered_sibling_breaks_smt():
    bundle = json.loads(json.dumps(VECTORS["inclusion_bundle"]))
    sibs = bundle["smt_proof"]["siblings"]
    sibs[0][0] ^= 0xFF  # flip a byte in the deepest sibling
    root = bytes.fromhex(VECTORS["manifest_root"])
    assert verify(bundle, root) is Verdict.SMT_INVALID


@pytest.mark.parametrize(
    "bad",
    [
        {},  # empty
        {"manifest_root": "zz", "kind": "inclusion", "smt_proof": {}},  # bad hex
        {"kind": "inclusion", "smt_proof": {}},  # missing manifest_root
        {  # missing identity fields
            "manifest_root": "00" * 32,
            "kind": "inclusion",
            "smt_proof": {},
        },
        "not a dict",
        12345,
    ],
)
def test_malformed_bundles_never_raise(bad):
    # Untrusted input must yield a deterministic Verdict, never an exception.
    v = verify(bad, b"\x00" * 32)
    assert v in (Verdict.MALFORMED, Verdict.ROOT_MISMATCH)
    assert not v.is_valid


def test_smt_verifiers_never_raise_on_garbage():
    from olympus_manifest import smt

    assert smt.verify_existence({}, b"\x00" * 32) is False
    assert smt.verify_existence({"siblings": "nope"}, None) is False
    assert smt.verify_nonexistence({"key": "zz", "siblings": []}, None) is False
    # Wrong sibling count and bad byte arrays must not raise.
    assert smt.verify_existence({"root_hash": [0] * 32, "siblings": [[0]]}, None) is False


def test_verify_against_manifest_handles_bad_root():
    assert (
        verify_against_manifest(VECTORS["inclusion_bundle"], {"manifest_root": "zz"})
        is Verdict.MALFORMED
    )


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
