// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cdhs_smf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to update (insert or modify) a record
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard identifier (e.g., "watauga:2025:budget")
	ShardId string `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Record key components (type, id, version, etc.)
	RecordKey *RecordKey `protobuf:"bytes,2,opt,name=record_key,json=recordKey,proto3" json:"record_key,omitempty"`
	// Canonicalized record content (already canonicalized)
	CanonicalContent []byte `protobuf:"bytes,3,opt,name=canonical_content,json=canonicalContent,proto3" json:"canonical_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *UpdateRequest) GetRecordKey() *RecordKey {
	if x != nil {
		return x.RecordKey
	}
	return nil
}

func (x *UpdateRequest) GetCanonicalContent() []byte {
	if x != nil {
		return x.CanonicalContent
	}
	return nil
}

// Response from update operation
type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new root hash after update
	NewRoot []byte `protobuf:"bytes,1,opt,name=new_root,json=newRoot,proto3" json:"new_root,omitempty"`
	// The global key that was computed
	GlobalKey []byte `protobuf:"bytes,2,opt,name=global_key,json=globalKey,proto3" json:"global_key,omitempty"`
	// The leaf value hash that was stored
	LeafValueHash []byte `protobuf:"bytes,3,opt,name=leaf_value_hash,json=leafValueHash,proto3" json:"leaf_value_hash,omitempty"`
	// SMT node deltas (for persistence)
	Deltas []*SmtNodeDelta `protobuf:"bytes,4,rep,name=deltas,proto3" json:"deltas,omitempty"`
	// Tree size after this update (number of non-empty leaves)
	TreeSize      uint64 `protobuf:"varint,5,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetNewRoot() []byte {
	if x != nil {
		return x.NewRoot
	}
	return nil
}

func (x *UpdateResponse) GetGlobalKey() []byte {
	if x != nil {
		return x.GlobalKey
	}
	return nil
}

func (x *UpdateResponse) GetLeafValueHash() []byte {
	if x != nil {
		return x.LeafValueHash
	}
	return nil
}

func (x *UpdateResponse) GetDeltas() []*SmtNodeDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

func (x *UpdateResponse) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

// Record key components
type RecordKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record type (e.g., "doc", "dataset", "appeal")
	RecordType string `protobuf:"bytes,1,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	// Record ID
	RecordId string `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// Version (optional)
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Additional metadata (for future extensibility)
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordKey) Reset() {
	*x = RecordKey{}
	mi := &file_cdhs_smf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordKey) ProtoMessage() {}

func (x *RecordKey) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordKey.ProtoReflect.Descriptor instead.
func (*RecordKey) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{2}
}

func (x *RecordKey) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *RecordKey) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordKey) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RecordKey) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SMT node delta for persistence
type SmtNodeDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the node (256 bits as bytes)
	Path []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Level in the tree (0-255)
	Level uint32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	// New hash value
	Hash          []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtNodeDelta) Reset() {
	*x = SmtNodeDelta{}
	mi := &file_cdhs_smf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtNodeDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtNodeDelta) ProtoMessage() {}

func (x *SmtNodeDelta) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtNodeDelta.ProtoReflect.Descriptor instead.
func (*SmtNodeDelta) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{3}
}

func (x *SmtNodeDelta) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SmtNodeDelta) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SmtNodeDelta) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Request to prove inclusion
type ProveInclusionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard identifier
	ShardId string `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Record key
	RecordKey *RecordKey `protobuf:"bytes,2,opt,name=record_key,json=recordKey,proto3" json:"record_key,omitempty"`
	// Root hash to prove against (optional, uses current if not specified)
	Root          []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveInclusionRequest) Reset() {
	*x = ProveInclusionRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveInclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveInclusionRequest) ProtoMessage() {}

func (x *ProveInclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveInclusionRequest.ProtoReflect.Descriptor instead.
func (*ProveInclusionRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{4}
}

func (x *ProveInclusionRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ProveInclusionRequest) GetRecordKey() *RecordKey {
	if x != nil {
		return x.RecordKey
	}
	return nil
}

func (x *ProveInclusionRequest) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Response with inclusion proof
type ProveInclusionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global key
	GlobalKey []byte `protobuf:"bytes,1,opt,name=global_key,json=globalKey,proto3" json:"global_key,omitempty"`
	// The leaf value hash
	ValueHash []byte `protobuf:"bytes,2,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	// Sibling hashes along the path (256 siblings)
	Siblings [][]byte `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	// Root hash
	Root          []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveInclusionResponse) Reset() {
	*x = ProveInclusionResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveInclusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveInclusionResponse) ProtoMessage() {}

func (x *ProveInclusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveInclusionResponse.ProtoReflect.Descriptor instead.
func (*ProveInclusionResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{5}
}

func (x *ProveInclusionResponse) GetGlobalKey() []byte {
	if x != nil {
		return x.GlobalKey
	}
	return nil
}

func (x *ProveInclusionResponse) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *ProveInclusionResponse) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *ProveInclusionResponse) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Request to verify inclusion
type VerifyInclusionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global key
	GlobalKey []byte `protobuf:"bytes,1,opt,name=global_key,json=globalKey,proto3" json:"global_key,omitempty"`
	// Leaf value hash
	ValueHash []byte `protobuf:"bytes,2,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	// Sibling hashes
	Siblings [][]byte `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	// Root hash to verify against
	Root          []byte `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyInclusionRequest) Reset() {
	*x = VerifyInclusionRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyInclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInclusionRequest) ProtoMessage() {}

func (x *VerifyInclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInclusionRequest.ProtoReflect.Descriptor instead.
func (*VerifyInclusionRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyInclusionRequest) GetGlobalKey() []byte {
	if x != nil {
		return x.GlobalKey
	}
	return nil
}

func (x *VerifyInclusionRequest) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *VerifyInclusionRequest) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *VerifyInclusionRequest) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Response from verification
type VerifyInclusionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the proof is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Error message if invalid
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyInclusionResponse) Reset() {
	*x = VerifyInclusionResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyInclusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInclusionResponse) ProtoMessage() {}

func (x *VerifyInclusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInclusionResponse.ProtoReflect.Descriptor instead.
func (*VerifyInclusionResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyInclusionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyInclusionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to prove non-inclusion
type ProveNonInclusionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard identifier
	ShardId string `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Record key
	RecordKey *RecordKey `protobuf:"bytes,2,opt,name=record_key,json=recordKey,proto3" json:"record_key,omitempty"`
	// Root hash to prove against (optional, uses current if not specified)
	Root          []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveNonInclusionRequest) Reset() {
	*x = ProveNonInclusionRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveNonInclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveNonInclusionRequest) ProtoMessage() {}

func (x *ProveNonInclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveNonInclusionRequest.ProtoReflect.Descriptor instead.
func (*ProveNonInclusionRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{8}
}

func (x *ProveNonInclusionRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ProveNonInclusionRequest) GetRecordKey() *RecordKey {
	if x != nil {
		return x.RecordKey
	}
	return nil
}

func (x *ProveNonInclusionRequest) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Response with non-inclusion proof
type ProveNonInclusionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global key
	GlobalKey []byte `protobuf:"bytes,1,opt,name=global_key,json=globalKey,proto3" json:"global_key,omitempty"`
	// Sibling hashes along the path to empty leaf
	Siblings [][]byte `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"`
	// Root hash
	Root          []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveNonInclusionResponse) Reset() {
	*x = ProveNonInclusionResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveNonInclusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveNonInclusionResponse) ProtoMessage() {}

func (x *ProveNonInclusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveNonInclusionResponse.ProtoReflect.Descriptor instead.
func (*ProveNonInclusionResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{9}
}

func (x *ProveNonInclusionResponse) GetGlobalKey() []byte {
	if x != nil {
		return x.GlobalKey
	}
	return nil
}

func (x *ProveNonInclusionResponse) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *ProveNonInclusionResponse) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Request to verify non-inclusion
type VerifyNonInclusionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global key
	GlobalKey []byte `protobuf:"bytes,1,opt,name=global_key,json=globalKey,proto3" json:"global_key,omitempty"`
	// Sibling hashes
	Siblings [][]byte `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"`
	// Root hash to verify against
	Root          []byte `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNonInclusionRequest) Reset() {
	*x = VerifyNonInclusionRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNonInclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNonInclusionRequest) ProtoMessage() {}

func (x *VerifyNonInclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNonInclusionRequest.ProtoReflect.Descriptor instead.
func (*VerifyNonInclusionRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyNonInclusionRequest) GetGlobalKey() []byte {
	if x != nil {
		return x.GlobalKey
	}
	return nil
}

func (x *VerifyNonInclusionRequest) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *VerifyNonInclusionRequest) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

// Response from non-inclusion verification
type VerifyNonInclusionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the proof is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Error message if invalid
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNonInclusionResponse) Reset() {
	*x = VerifyNonInclusionResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNonInclusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNonInclusionResponse) ProtoMessage() {}

func (x *VerifyNonInclusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNonInclusionResponse.ProtoReflect.Descriptor instead.
func (*VerifyNonInclusionResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyNonInclusionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyNonInclusionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to canonicalize content
type CanonicalizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content type (e.g., "json", "html", "xml")
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Raw content
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalizeRequest) Reset() {
	*x = CanonicalizeRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalizeRequest) ProtoMessage() {}

func (x *CanonicalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalizeRequest.ProtoReflect.Descriptor instead.
func (*CanonicalizeRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{12}
}

func (x *CanonicalizeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CanonicalizeRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Response with canonicalized content
type CanonicalizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonicalized content
	CanonicalContent []byte `protobuf:"bytes,1,opt,name=canonical_content,json=canonicalContent,proto3" json:"canonical_content,omitempty"`
	// Hash of canonicalized content
	ContentHash   []byte `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalizeResponse) Reset() {
	*x = CanonicalizeResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalizeResponse) ProtoMessage() {}

func (x *CanonicalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalizeResponse.ProtoReflect.Descriptor instead.
func (*CanonicalizeResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{13}
}

func (x *CanonicalizeResponse) GetCanonicalContent() []byte {
	if x != nil {
		return x.CanonicalContent
	}
	return nil
}

func (x *CanonicalizeResponse) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

// Request to get current root
type GetRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootRequest) Reset() {
	*x = GetRootRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootRequest) ProtoMessage() {}

func (x *GetRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootRequest.ProtoReflect.Descriptor instead.
func (*GetRootRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{14}
}

// Response with current root
type GetRootResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current root hash
	Root []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Tree size (number of non-empty leaves)
	TreeSize      uint64 `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootResponse) Reset() {
	*x = GetRootResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootResponse) ProtoMessage() {}

func (x *GetRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootResponse.ProtoReflect.Descriptor instead.
func (*GetRootResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{15}
}

func (x *GetRootResponse) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *GetRootResponse) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

// Request to sign a root
type SignRootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root hash to sign
	Root []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Tree size at the time of signing
	TreeSize uint64 `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	// Additional context (e.g., shard_id, record_id)
	Context       map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRootRequest) Reset() {
	*x = SignRootRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRootRequest) ProtoMessage() {}

func (x *SignRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRootRequest.ProtoReflect.Descriptor instead.
func (*SignRootRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{16}
}

func (x *SignRootRequest) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SignRootRequest) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *SignRootRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Response with signature
type SignRootResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ed25519 signature
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Public key used for signing
	PublicKey     []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRootResponse) Reset() {
	*x = SignRootResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRootResponse) ProtoMessage() {}

func (x *SignRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRootResponse.ProtoReflect.Descriptor instead.
func (*SignRootResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{17}
}

func (x *SignRootResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignRootResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Request to replay persisted leaves into the in-memory SMT
type ReplayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of leaf entries to replay (insertion order, oldest first)
	Leaves        []*LeafEntry `protobuf:"bytes,1,rep,name=leaves,proto3" json:"leaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_cdhs_smf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{18}
}

func (x *ReplayRequest) GetLeaves() []*LeafEntry {
	if x != nil {
		return x.Leaves
	}
	return nil
}

// A single leaf entry for replay
type LeafEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte global key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 32-byte leaf value hash
	ValueHash     []byte `protobuf:"bytes,2,opt,name=value_hash,json=valueHash,proto3" json:"value_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafEntry) Reset() {
	*x = LeafEntry{}
	mi := &file_cdhs_smf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafEntry) ProtoMessage() {}

func (x *LeafEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafEntry.ProtoReflect.Descriptor instead.
func (*LeafEntry) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{19}
}

func (x *LeafEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LeafEntry) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

// Response from replay operation
type ReplayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final root hash after replaying all leaves
	RootHash      []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_cdhs_smf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdhs_smf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_cdhs_smf_proto_rawDescGZIP(), []int{20}
}

func (x *ReplayResponse) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

var File_cdhs_smf_proto protoreflect.FileDescriptor

const file_cdhs_smf_proto_rawDesc = "" +
	"\n" +
	"\x0ecdhs_smf.proto\x12\x13olympus.cdhs_smf.v1\"\x96\x01\n" +
	"\rUpdateRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12=\n" +
	"\n" +
	"record_key\x18\x02 \x01(\v2\x1e.olympus.cdhs_smf.v1.RecordKeyR\trecordKey\x12+\n" +
	"\x11canonical_content\x18\x03 \x01(\fR\x10canonicalContent\"\xca\x01\n" +
	"\x0eUpdateResponse\x12\x19\n" +
	"\bnew_root\x18\x01 \x01(\fR\anewRoot\x12\x1d\n" +
	"\n" +
	"global_key\x18\x02 \x01(\fR\tglobalKey\x12&\n" +
	"\x0fleaf_value_hash\x18\x03 \x01(\fR\rleafValueHash\x129\n" +
	"\x06deltas\x18\x04 \x03(\v2!.olympus.cdhs_smf.v1.SmtNodeDeltaR\x06deltas\x12\x1b\n" +
	"\ttree_size\x18\x05 \x01(\x04R\btreeSize\"\xea\x01\n" +
	"\tRecordKey\x12\x1f\n" +
	"\vrecord_type\x18\x01 \x01(\tR\n" +
	"recordType\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.olympus.cdhs_smf.v1.RecordKey.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\fSmtNodeDelta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"\x85\x01\n" +
	"\x15ProveInclusionRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12=\n" +
	"\n" +
	"record_key\x18\x02 \x01(\v2\x1e.olympus.cdhs_smf.v1.RecordKeyR\trecordKey\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\"\x86\x01\n" +
	"\x16ProveInclusionResponse\x12\x1d\n" +
	"\n" +
	"global_key\x18\x01 \x01(\fR\tglobalKey\x12\x1d\n" +
	"\n" +
	"value_hash\x18\x02 \x01(\fR\tvalueHash\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04root\x18\x04 \x01(\fR\x04root\"\x86\x01\n" +
	"\x16VerifyInclusionRequest\x12\x1d\n" +
	"\n" +
	"global_key\x18\x01 \x01(\fR\tglobalKey\x12\x1d\n" +
	"\n" +
	"value_hash\x18\x02 \x01(\fR\tvalueHash\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04root\x18\x04 \x01(\fR\x04root\"E\n" +
	"\x17VerifyInclusionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x88\x01\n" +
	"\x18ProveNonInclusionRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12=\n" +
	"\n" +
	"record_key\x18\x02 \x01(\v2\x1e.olympus.cdhs_smf.v1.RecordKeyR\trecordKey\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\"j\n" +
	"\x19ProveNonInclusionResponse\x12\x1d\n" +
	"\n" +
	"global_key\x18\x01 \x01(\fR\tglobalKey\x12\x1a\n" +
	"\bsiblings\x18\x02 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\"j\n" +
	"\x19VerifyNonInclusionRequest\x12\x1d\n" +
	"\n" +
	"global_key\x18\x01 \x01(\fR\tglobalKey\x12\x1a\n" +
	"\bsiblings\x18\x02 \x03(\fR\bsiblings\x12\x12\n" +
	"\x04root\x18\x03 \x01(\fR\x04root\"H\n" +
	"\x1aVerifyNonInclusionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x13CanonicalizeRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"f\n" +
	"\x14CanonicalizeResponse\x12+\n" +
	"\x11canonical_content\x18\x01 \x01(\fR\x10canonicalContent\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\fR\vcontentHash\"\x10\n" +
	"\x0eGetRootRequest\"B\n" +
	"\x0fGetRootResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\fR\x04root\x12\x1b\n" +
	"\ttree_size\x18\x02 \x01(\x04R\btreeSize\"\xcb\x01\n" +
	"\x0fSignRootRequest\x12\x12\n" +
	"\x04root\x18\x01 \x01(\fR\x04root\x12\x1b\n" +
	"\ttree_size\x18\x02 \x01(\x04R\btreeSize\x12K\n" +
	"\acontext\x18\x03 \x03(\v21.olympus.cdhs_smf.v1.SignRootRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x10SignRootResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"G\n" +
	"\rReplayRequest\x126\n" +
	"\x06leaves\x18\x01 \x03(\v2\x1e.olympus.cdhs_smf.v1.LeafEntryR\x06leaves\"<\n" +
	"\tLeafEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1d\n" +
	"\n" +
	"value_hash\x18\x02 \x01(\fR\tvalueHash\"-\n" +
	"\x0eReplayResponse\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash2\x94\a\n" +
	"\x0eCdhsSmfService\x12Q\n" +
	"\x06Update\x12\".olympus.cdhs_smf.v1.UpdateRequest\x1a#.olympus.cdhs_smf.v1.UpdateResponse\x12i\n" +
	"\x0eProveInclusion\x12*.olympus.cdhs_smf.v1.ProveInclusionRequest\x1a+.olympus.cdhs_smf.v1.ProveInclusionResponse\x12l\n" +
	"\x0fVerifyInclusion\x12+.olympus.cdhs_smf.v1.VerifyInclusionRequest\x1a,.olympus.cdhs_smf.v1.VerifyInclusionResponse\x12r\n" +
	"\x11ProveNonInclusion\x12-.olympus.cdhs_smf.v1.ProveNonInclusionRequest\x1a..olympus.cdhs_smf.v1.ProveNonInclusionResponse\x12u\n" +
	"\x12VerifyNonInclusion\x12..olympus.cdhs_smf.v1.VerifyNonInclusionRequest\x1a/.olympus.cdhs_smf.v1.VerifyNonInclusionResponse\x12c\n" +
	"\fCanonicalize\x12(.olympus.cdhs_smf.v1.CanonicalizeRequest\x1a).olympus.cdhs_smf.v1.CanonicalizeResponse\x12T\n" +
	"\aGetRoot\x12#.olympus.cdhs_smf.v1.GetRootRequest\x1a$.olympus.cdhs_smf.v1.GetRootResponse\x12W\n" +
	"\bSignRoot\x12$.olympus.cdhs_smf.v1.SignRootRequest\x1a%.olympus.cdhs_smf.v1.SignRootResponse\x12W\n" +
	"\fReplayLeaves\x12\".olympus.cdhs_smf.v1.ReplayRequest\x1a#.olympus.cdhs_smf.v1.ReplayResponseBCZAgithub.com/wombatvagina69-crypto/olympus/services/sequencer/protob\x06proto3"

var (
	file_cdhs_smf_proto_rawDescOnce sync.Once
	file_cdhs_smf_proto_rawDescData []byte
)

func file_cdhs_smf_proto_rawDescGZIP() []byte {
	file_cdhs_smf_proto_rawDescOnce.Do(func() {
		file_cdhs_smf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdhs_smf_proto_rawDesc), len(file_cdhs_smf_proto_rawDesc)))
	})
	return file_cdhs_smf_proto_rawDescData
}

var file_cdhs_smf_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cdhs_smf_proto_goTypes = []any{
	(*UpdateRequest)(nil),              // 0: olympus.cdhs_smf.v1.UpdateRequest
	(*UpdateResponse)(nil),             // 1: olympus.cdhs_smf.v1.UpdateResponse
	(*RecordKey)(nil),                  // 2: olympus.cdhs_smf.v1.RecordKey
	(*SmtNodeDelta)(nil),               // 3: olympus.cdhs_smf.v1.SmtNodeDelta
	(*ProveInclusionRequest)(nil),      // 4: olympus.cdhs_smf.v1.ProveInclusionRequest
	(*ProveInclusionResponse)(nil),     // 5: olympus.cdhs_smf.v1.ProveInclusionResponse
	(*VerifyInclusionRequest)(nil),     // 6: olympus.cdhs_smf.v1.VerifyInclusionRequest
	(*VerifyInclusionResponse)(nil),    // 7: olympus.cdhs_smf.v1.VerifyInclusionResponse
	(*ProveNonInclusionRequest)(nil),   // 8: olympus.cdhs_smf.v1.ProveNonInclusionRequest
	(*ProveNonInclusionResponse)(nil),  // 9: olympus.cdhs_smf.v1.ProveNonInclusionResponse
	(*VerifyNonInclusionRequest)(nil),  // 10: olympus.cdhs_smf.v1.VerifyNonInclusionRequest
	(*VerifyNonInclusionResponse)(nil), // 11: olympus.cdhs_smf.v1.VerifyNonInclusionResponse
	(*CanonicalizeRequest)(nil),        // 12: olympus.cdhs_smf.v1.CanonicalizeRequest
	(*CanonicalizeResponse)(nil),       // 13: olympus.cdhs_smf.v1.CanonicalizeResponse
	(*GetRootRequest)(nil),             // 14: olympus.cdhs_smf.v1.GetRootRequest
	(*GetRootResponse)(nil),            // 15: olympus.cdhs_smf.v1.GetRootResponse
	(*SignRootRequest)(nil),            // 16: olympus.cdhs_smf.v1.SignRootRequest
	(*SignRootResponse)(nil),           // 17: olympus.cdhs_smf.v1.SignRootResponse
	(*ReplayRequest)(nil),              // 18: olympus.cdhs_smf.v1.ReplayRequest
	(*LeafEntry)(nil),                  // 19: olympus.cdhs_smf.v1.LeafEntry
	(*ReplayResponse)(nil),             // 20: olympus.cdhs_smf.v1.ReplayResponse
	nil,                                // 21: olympus.cdhs_smf.v1.RecordKey.MetadataEntry
	nil,                                // 22: olympus.cdhs_smf.v1.SignRootRequest.ContextEntry
}
var file_cdhs_smf_proto_depIdxs = []int32{
	2,  // 0: olympus.cdhs_smf.v1.UpdateRequest.record_key:type_name -> olympus.cdhs_smf.v1.RecordKey
	3,  // 1: olympus.cdhs_smf.v1.UpdateResponse.deltas:type_name -> olympus.cdhs_smf.v1.SmtNodeDelta
	21, // 2: olympus.cdhs_smf.v1.RecordKey.metadata:type_name -> olympus.cdhs_smf.v1.RecordKey.MetadataEntry
	2,  // 3: olympus.cdhs_smf.v1.ProveInclusionRequest.record_key:type_name -> olympus.cdhs_smf.v1.RecordKey
	2,  // 4: olympus.cdhs_smf.v1.ProveNonInclusionRequest.record_key:type_name -> olympus.cdhs_smf.v1.RecordKey
	22, // 5: olympus.cdhs_smf.v1.SignRootRequest.context:type_name -> olympus.cdhs_smf.v1.SignRootRequest.ContextEntry
	19, // 6: olympus.cdhs_smf.v1.ReplayRequest.leaves:type_name -> olympus.cdhs_smf.v1.LeafEntry
	0,  // 7: olympus.cdhs_smf.v1.CdhsSmfService.Update:input_type -> olympus.cdhs_smf.v1.UpdateRequest
	4,  // 8: olympus.cdhs_smf.v1.CdhsSmfService.ProveInclusion:input_type -> olympus.cdhs_smf.v1.ProveInclusionRequest
	6,  // 9: olympus.cdhs_smf.v1.CdhsSmfService.VerifyInclusion:input_type -> olympus.cdhs_smf.v1.VerifyInclusionRequest
	8,  // 10: olympus.cdhs_smf.v1.CdhsSmfService.ProveNonInclusion:input_type -> olympus.cdhs_smf.v1.ProveNonInclusionRequest
	10, // 11: olympus.cdhs_smf.v1.CdhsSmfService.VerifyNonInclusion:input_type -> olympus.cdhs_smf.v1.VerifyNonInclusionRequest
	12, // 12: olympus.cdhs_smf.v1.CdhsSmfService.Canonicalize:input_type -> olympus.cdhs_smf.v1.CanonicalizeRequest
	14, // 13: olympus.cdhs_smf.v1.CdhsSmfService.GetRoot:input_type -> olympus.cdhs_smf.v1.GetRootRequest
	16, // 14: olympus.cdhs_smf.v1.CdhsSmfService.SignRoot:input_type -> olympus.cdhs_smf.v1.SignRootRequest
	18, // 15: olympus.cdhs_smf.v1.CdhsSmfService.ReplayLeaves:input_type -> olympus.cdhs_smf.v1.ReplayRequest
	1,  // 16: olympus.cdhs_smf.v1.CdhsSmfService.Update:output_type -> olympus.cdhs_smf.v1.UpdateResponse
	5,  // 17: olympus.cdhs_smf.v1.CdhsSmfService.ProveInclusion:output_type -> olympus.cdhs_smf.v1.ProveInclusionResponse
	7,  // 18: olympus.cdhs_smf.v1.CdhsSmfService.VerifyInclusion:output_type -> olympus.cdhs_smf.v1.VerifyInclusionResponse
	9,  // 19: olympus.cdhs_smf.v1.CdhsSmfService.ProveNonInclusion:output_type -> olympus.cdhs_smf.v1.ProveNonInclusionResponse
	11, // 20: olympus.cdhs_smf.v1.CdhsSmfService.VerifyNonInclusion:output_type -> olympus.cdhs_smf.v1.VerifyNonInclusionResponse
	13, // 21: olympus.cdhs_smf.v1.CdhsSmfService.Canonicalize:output_type -> olympus.cdhs_smf.v1.CanonicalizeResponse
	15, // 22: olympus.cdhs_smf.v1.CdhsSmfService.GetRoot:output_type -> olympus.cdhs_smf.v1.GetRootResponse
	17, // 23: olympus.cdhs_smf.v1.CdhsSmfService.SignRoot:output_type -> olympus.cdhs_smf.v1.SignRootResponse
	20, // 24: olympus.cdhs_smf.v1.CdhsSmfService.ReplayLeaves:output_type -> olympus.cdhs_smf.v1.ReplayResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cdhs_smf_proto_init() }
func file_cdhs_smf_proto_init() {
	if File_cdhs_smf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdhs_smf_proto_rawDesc), len(file_cdhs_smf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdhs_smf_proto_goTypes,
		DependencyIndexes: file_cdhs_smf_proto_depIdxs,
		MessageInfos:      file_cdhs_smf_proto_msgTypes,
	}.Build()
	File_cdhs_smf_proto = out.File
	file_cdhs_smf_proto_goTypes = nil
	file_cdhs_smf_proto_depIdxs = nil
}
