// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cdhs_smf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CdhsSmfService_Update_FullMethodName             = "/olympus.cdhs_smf.v1.CdhsSmfService/Update"
	CdhsSmfService_ProveInclusion_FullMethodName     = "/olympus.cdhs_smf.v1.CdhsSmfService/ProveInclusion"
	CdhsSmfService_VerifyInclusion_FullMethodName    = "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyInclusion"
	CdhsSmfService_ProveNonInclusion_FullMethodName  = "/olympus.cdhs_smf.v1.CdhsSmfService/ProveNonInclusion"
	CdhsSmfService_VerifyNonInclusion_FullMethodName = "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyNonInclusion"
	CdhsSmfService_Canonicalize_FullMethodName       = "/olympus.cdhs_smf.v1.CdhsSmfService/Canonicalize"
	CdhsSmfService_GetRoot_FullMethodName            = "/olympus.cdhs_smf.v1.CdhsSmfService/GetRoot"
	CdhsSmfService_SignRoot_FullMethodName           = "/olympus.cdhs_smf.v1.CdhsSmfService/SignRoot"
)

// CdhsSmfServiceClient is the client API for CdhsSmfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CdhsSmfServiceClient interface {
	// Insert or update a record in the global SMT
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Generate an inclusion proof for a key
	ProveInclusion(ctx context.Context, in *ProveInclusionRequest, opts ...grpc.CallOption) (*ProveInclusionResponse, error)
	// Verify an inclusion proof
	VerifyInclusion(ctx context.Context, in *VerifyInclusionRequest, opts ...grpc.CallOption) (*VerifyInclusionResponse, error)
	// Generate a non-inclusion proof for a key
	ProveNonInclusion(ctx context.Context, in *ProveNonInclusionRequest, opts ...grpc.CallOption) (*ProveNonInclusionResponse, error)
	// Verify a non-inclusion proof
	VerifyNonInclusion(ctx context.Context, in *VerifyNonInclusionRequest, opts ...grpc.CallOption) (*VerifyNonInclusionResponse, error)
	// Canonicalize a record (for consistency)
	Canonicalize(ctx context.Context, in *CanonicalizeRequest, opts ...grpc.CallOption) (*CanonicalizeResponse, error)
	// Get the current root hash
	GetRoot(ctx context.Context, in *GetRootRequest, opts ...grpc.CallOption) (*GetRootResponse, error)
	// Sign a root hash with Ed25519
	SignRoot(ctx context.Context, in *SignRootRequest, opts ...grpc.CallOption) (*SignRootResponse, error)
}

type cdhsSmfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCdhsSmfServiceClient(cc grpc.ClientConnInterface) CdhsSmfServiceClient {
	return &cdhsSmfServiceClient{cc}
}

func (c *cdhsSmfServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) ProveInclusion(ctx context.Context, in *ProveInclusionRequest, opts ...grpc.CallOption) (*ProveInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_ProveInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) VerifyInclusion(ctx context.Context, in *VerifyInclusionRequest, opts ...grpc.CallOption) (*VerifyInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_VerifyInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) ProveNonInclusion(ctx context.Context, in *ProveNonInclusionRequest, opts ...grpc.CallOption) (*ProveNonInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveNonInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_ProveNonInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) VerifyNonInclusion(ctx context.Context, in *VerifyNonInclusionRequest, opts ...grpc.CallOption) (*VerifyNonInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyNonInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_VerifyNonInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) Canonicalize(ctx context.Context, in *CanonicalizeRequest, opts ...grpc.CallOption) (*CanonicalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanonicalizeResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_Canonicalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) GetRoot(ctx context.Context, in *GetRootRequest, opts ...grpc.CallOption) (*GetRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_GetRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) SignRoot(ctx context.Context, in *SignRootRequest, opts ...grpc.CallOption) (*SignRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignRootResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_SignRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdhsSmfServiceServer is the server API for CdhsSmfService service.
// All implementations must embed UnimplementedCdhsSmfServiceServer
// for forward compatibility.
type CdhsSmfServiceServer interface {
	// Insert or update a record in the global SMT
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// Generate an inclusion proof for a key
	ProveInclusion(context.Context, *ProveInclusionRequest) (*ProveInclusionResponse, error)
	// Verify an inclusion proof
	VerifyInclusion(context.Context, *VerifyInclusionRequest) (*VerifyInclusionResponse, error)
	// Generate a non-inclusion proof for a key
	ProveNonInclusion(context.Context, *ProveNonInclusionRequest) (*ProveNonInclusionResponse, error)
	// Verify a non-inclusion proof
	VerifyNonInclusion(context.Context, *VerifyNonInclusionRequest) (*VerifyNonInclusionResponse, error)
	// Canonicalize a record (for consistency)
	Canonicalize(context.Context, *CanonicalizeRequest) (*CanonicalizeResponse, error)
	// Get the current root hash
	GetRoot(context.Context, *GetRootRequest) (*GetRootResponse, error)
	// Sign a root hash with Ed25519
	SignRoot(context.Context, *SignRootRequest) (*SignRootResponse, error)
	mustEmbedUnimplementedCdhsSmfServiceServer()
}

// UnimplementedCdhsSmfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCdhsSmfServiceServer struct{}

func (UnimplementedCdhsSmfServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCdhsSmfServiceServer) ProveInclusion(context.Context, *ProveInclusionRequest) (*ProveInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) VerifyInclusion(context.Context, *VerifyInclusionRequest) (*VerifyInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) ProveNonInclusion(context.Context, *ProveNonInclusionRequest) (*ProveNonInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveNonInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) VerifyNonInclusion(context.Context, *VerifyNonInclusionRequest) (*VerifyNonInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyNonInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) Canonicalize(context.Context, *CanonicalizeRequest) (*CanonicalizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Canonicalize not implemented")
}
func (UnimplementedCdhsSmfServiceServer) GetRoot(context.Context, *GetRootRequest) (*GetRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoot not implemented")
}
func (UnimplementedCdhsSmfServiceServer) SignRoot(context.Context, *SignRootRequest) (*SignRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignRoot not implemented")
}
func (UnimplementedCdhsSmfServiceServer) mustEmbedUnimplementedCdhsSmfServiceServer() {}
func (UnimplementedCdhsSmfServiceServer) testEmbeddedByValue()                        {}

// UnsafeCdhsSmfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdhsSmfServiceServer will
// result in compilation errors.
type UnsafeCdhsSmfServiceServer interface {
	mustEmbedUnimplementedCdhsSmfServiceServer()
}

func RegisterCdhsSmfServiceServer(s grpc.ServiceRegistrar, srv CdhsSmfServiceServer) {
	// If the following call panics, it indicates UnimplementedCdhsSmfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CdhsSmfService_ServiceDesc, srv)
}

func _CdhsSmfService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_ProveInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).ProveInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_ProveInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).ProveInclusion(ctx, req.(*ProveInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_VerifyInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).VerifyInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_VerifyInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).VerifyInclusion(ctx, req.(*VerifyInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_ProveNonInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNonInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).ProveNonInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_ProveNonInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).ProveNonInclusion(ctx, req.(*ProveNonInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_VerifyNonInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyNonInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).VerifyNonInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_VerifyNonInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).VerifyNonInclusion(ctx, req.(*VerifyNonInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_Canonicalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanonicalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).Canonicalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_Canonicalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).Canonicalize(ctx, req.(*CanonicalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_GetRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).GetRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_GetRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).GetRoot(ctx, req.(*GetRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_SignRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).SignRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_SignRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).SignRoot(ctx, req.(*SignRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CdhsSmfService_ServiceDesc is the grpc.ServiceDesc for CdhsSmfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CdhsSmfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olympus.cdhs_smf.v1.CdhsSmfService",
	HandlerType: (*CdhsSmfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _CdhsSmfService_Update_Handler,
		},
		{
			MethodName: "ProveInclusion",
			Handler:    _CdhsSmfService_ProveInclusion_Handler,
		},
		{
			MethodName: "VerifyInclusion",
			Handler:    _CdhsSmfService_VerifyInclusion_Handler,
		},
		{
			MethodName: "ProveNonInclusion",
			Handler:    _CdhsSmfService_ProveNonInclusion_Handler,
		},
		{
			MethodName: "VerifyNonInclusion",
			Handler:    _CdhsSmfService_VerifyNonInclusion_Handler,
		},
		{
			MethodName: "Canonicalize",
			Handler:    _CdhsSmfService_Canonicalize_Handler,
		},
		{
			MethodName: "GetRoot",
			Handler:    _CdhsSmfService_GetRoot_Handler,
		},
		{
			MethodName: "SignRoot",
			Handler:    _CdhsSmfService_SignRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdhs_smf.proto",
}
