// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cdhs_smf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CdhsSmfService_Update_FullMethodName               = "/olympus.cdhs_smf.v1.CdhsSmfService/Update"
	CdhsSmfService_PrepareUpdate_FullMethodName        = "/olympus.cdhs_smf.v1.CdhsSmfService/PrepareUpdate"
	CdhsSmfService_CommitPreparedUpdate_FullMethodName = "/olympus.cdhs_smf.v1.CdhsSmfService/CommitPreparedUpdate"
	CdhsSmfService_AbortPreparedUpdate_FullMethodName  = "/olympus.cdhs_smf.v1.CdhsSmfService/AbortPreparedUpdate"
	CdhsSmfService_ProveInclusion_FullMethodName       = "/olympus.cdhs_smf.v1.CdhsSmfService/ProveInclusion"
	CdhsSmfService_VerifyInclusion_FullMethodName      = "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyInclusion"
	CdhsSmfService_ProveNonInclusion_FullMethodName    = "/olympus.cdhs_smf.v1.CdhsSmfService/ProveNonInclusion"
	CdhsSmfService_VerifyNonInclusion_FullMethodName   = "/olympus.cdhs_smf.v1.CdhsSmfService/VerifyNonInclusion"
	CdhsSmfService_Canonicalize_FullMethodName         = "/olympus.cdhs_smf.v1.CdhsSmfService/Canonicalize"
	CdhsSmfService_GetRoot_FullMethodName              = "/olympus.cdhs_smf.v1.CdhsSmfService/GetRoot"
	CdhsSmfService_SignRoot_FullMethodName             = "/olympus.cdhs_smf.v1.CdhsSmfService/SignRoot"
	CdhsSmfService_ReplayLeaves_FullMethodName         = "/olympus.cdhs_smf.v1.CdhsSmfService/ReplayLeaves"
)

// CdhsSmfServiceClient is the client API for CdhsSmfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CdhsSmfServiceClient interface {
	// Insert or update a record in the global SMT.
	//
	// DEPRECATED for write paths that require crash safety: this RPC mutates
	// the in-memory SMT immediately, before any external storage durability
	// step. Sequencers MUST use the two-phase
	// PrepareUpdate / CommitPreparedUpdate flow (see H-2) so that durable
	// (Postgres) state and live (Rust) state cannot diverge on storage failure.
	// Update() is retained for tests and for callers that have no external
	// durability requirements.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Phase 1 of two-phase commit: compute the new root + deltas for an update
	// WITHOUT mutating the live in-memory SMT. The prepared transaction is
	// held in a bounded LRU keyed by transaction_id; the caller MUST follow
	// up with either CommitPreparedUpdate or AbortPreparedUpdate. Prepared
	// transactions whose TTL elapses are evicted and treated as aborted.
	//
	// A prepared-but-uncommitted update MUST NOT appear in any signed root
	// or proof returned by GetRoot / ProveInclusion / Update.
	PrepareUpdate(ctx context.Context, in *PrepareUpdateRequest, opts ...grpc.CallOption) (*PrepareUpdateResponse, error)
	// Phase 2 of two-phase commit: atomically apply a previously prepared
	// update to the live SMT. Returns NOT_FOUND if the transaction id is
	// unknown (already committed, aborted, or evicted), or FAILED_PRECONDITION
	// if another commit has advanced the root since the transaction was
	// prepared (the caller should Abort and re-prepare).
	CommitPreparedUpdate(ctx context.Context, in *CommitPreparedUpdateRequest, opts ...grpc.CallOption) (*CommitPreparedUpdateResponse, error)
	// Discard a prepared transaction. Idempotent: returns OK whether or not
	// the transaction is currently in the prepared store. Callers MUST invoke
	// this on any failure path between PrepareUpdate and CommitPreparedUpdate
	// so that the prepared LRU does not fill up with abandoned entries.
	AbortPreparedUpdate(ctx context.Context, in *AbortPreparedUpdateRequest, opts ...grpc.CallOption) (*AbortPreparedUpdateResponse, error)
	// Generate an inclusion proof for a key
	ProveInclusion(ctx context.Context, in *ProveInclusionRequest, opts ...grpc.CallOption) (*ProveInclusionResponse, error)
	// Verify an inclusion proof
	VerifyInclusion(ctx context.Context, in *VerifyInclusionRequest, opts ...grpc.CallOption) (*VerifyInclusionResponse, error)
	// Generate a non-inclusion proof for a key
	ProveNonInclusion(ctx context.Context, in *ProveNonInclusionRequest, opts ...grpc.CallOption) (*ProveNonInclusionResponse, error)
	// Verify a non-inclusion proof
	VerifyNonInclusion(ctx context.Context, in *VerifyNonInclusionRequest, opts ...grpc.CallOption) (*VerifyNonInclusionResponse, error)
	// Canonicalize a record (for consistency)
	Canonicalize(ctx context.Context, in *CanonicalizeRequest, opts ...grpc.CallOption) (*CanonicalizeResponse, error)
	// Get the current root hash
	GetRoot(ctx context.Context, in *GetRootRequest, opts ...grpc.CallOption) (*GetRootResponse, error)
	// Sign a root hash with Ed25519
	SignRoot(ctx context.Context, in *SignRootRequest, opts ...grpc.CallOption) (*SignRootResponse, error)
	// Replay persisted leaves into the in-memory SMT at startup
	ReplayLeaves(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
}

type cdhsSmfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCdhsSmfServiceClient(cc grpc.ClientConnInterface) CdhsSmfServiceClient {
	return &cdhsSmfServiceClient{cc}
}

func (c *cdhsSmfServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) PrepareUpdate(ctx context.Context, in *PrepareUpdateRequest, opts ...grpc.CallOption) (*PrepareUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareUpdateResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_PrepareUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) CommitPreparedUpdate(ctx context.Context, in *CommitPreparedUpdateRequest, opts ...grpc.CallOption) (*CommitPreparedUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPreparedUpdateResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_CommitPreparedUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) AbortPreparedUpdate(ctx context.Context, in *AbortPreparedUpdateRequest, opts ...grpc.CallOption) (*AbortPreparedUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortPreparedUpdateResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_AbortPreparedUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) ProveInclusion(ctx context.Context, in *ProveInclusionRequest, opts ...grpc.CallOption) (*ProveInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_ProveInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) VerifyInclusion(ctx context.Context, in *VerifyInclusionRequest, opts ...grpc.CallOption) (*VerifyInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_VerifyInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) ProveNonInclusion(ctx context.Context, in *ProveNonInclusionRequest, opts ...grpc.CallOption) (*ProveNonInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveNonInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_ProveNonInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) VerifyNonInclusion(ctx context.Context, in *VerifyNonInclusionRequest, opts ...grpc.CallOption) (*VerifyNonInclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyNonInclusionResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_VerifyNonInclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) Canonicalize(ctx context.Context, in *CanonicalizeRequest, opts ...grpc.CallOption) (*CanonicalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanonicalizeResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_Canonicalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) GetRoot(ctx context.Context, in *GetRootRequest, opts ...grpc.CallOption) (*GetRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_GetRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) SignRoot(ctx context.Context, in *SignRootRequest, opts ...grpc.CallOption) (*SignRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignRootResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_SignRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdhsSmfServiceClient) ReplayLeaves(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, CdhsSmfService_ReplayLeaves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdhsSmfServiceServer is the server API for CdhsSmfService service.
// All implementations must embed UnimplementedCdhsSmfServiceServer
// for forward compatibility.
type CdhsSmfServiceServer interface {
	// Insert or update a record in the global SMT.
	//
	// DEPRECATED for write paths that require crash safety: this RPC mutates
	// the in-memory SMT immediately, before any external storage durability
	// step. Sequencers MUST use the two-phase
	// PrepareUpdate / CommitPreparedUpdate flow (see H-2) so that durable
	// (Postgres) state and live (Rust) state cannot diverge on storage failure.
	// Update() is retained for tests and for callers that have no external
	// durability requirements.
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// Phase 1 of two-phase commit: compute the new root + deltas for an update
	// WITHOUT mutating the live in-memory SMT. The prepared transaction is
	// held in a bounded LRU keyed by transaction_id; the caller MUST follow
	// up with either CommitPreparedUpdate or AbortPreparedUpdate. Prepared
	// transactions whose TTL elapses are evicted and treated as aborted.
	//
	// A prepared-but-uncommitted update MUST NOT appear in any signed root
	// or proof returned by GetRoot / ProveInclusion / Update.
	PrepareUpdate(context.Context, *PrepareUpdateRequest) (*PrepareUpdateResponse, error)
	// Phase 2 of two-phase commit: atomically apply a previously prepared
	// update to the live SMT. Returns NOT_FOUND if the transaction id is
	// unknown (already committed, aborted, or evicted), or FAILED_PRECONDITION
	// if another commit has advanced the root since the transaction was
	// prepared (the caller should Abort and re-prepare).
	CommitPreparedUpdate(context.Context, *CommitPreparedUpdateRequest) (*CommitPreparedUpdateResponse, error)
	// Discard a prepared transaction. Idempotent: returns OK whether or not
	// the transaction is currently in the prepared store. Callers MUST invoke
	// this on any failure path between PrepareUpdate and CommitPreparedUpdate
	// so that the prepared LRU does not fill up with abandoned entries.
	AbortPreparedUpdate(context.Context, *AbortPreparedUpdateRequest) (*AbortPreparedUpdateResponse, error)
	// Generate an inclusion proof for a key
	ProveInclusion(context.Context, *ProveInclusionRequest) (*ProveInclusionResponse, error)
	// Verify an inclusion proof
	VerifyInclusion(context.Context, *VerifyInclusionRequest) (*VerifyInclusionResponse, error)
	// Generate a non-inclusion proof for a key
	ProveNonInclusion(context.Context, *ProveNonInclusionRequest) (*ProveNonInclusionResponse, error)
	// Verify a non-inclusion proof
	VerifyNonInclusion(context.Context, *VerifyNonInclusionRequest) (*VerifyNonInclusionResponse, error)
	// Canonicalize a record (for consistency)
	Canonicalize(context.Context, *CanonicalizeRequest) (*CanonicalizeResponse, error)
	// Get the current root hash
	GetRoot(context.Context, *GetRootRequest) (*GetRootResponse, error)
	// Sign a root hash with Ed25519
	SignRoot(context.Context, *SignRootRequest) (*SignRootResponse, error)
	// Replay persisted leaves into the in-memory SMT at startup
	ReplayLeaves(context.Context, *ReplayRequest) (*ReplayResponse, error)
	mustEmbedUnimplementedCdhsSmfServiceServer()
}

// UnimplementedCdhsSmfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCdhsSmfServiceServer struct{}

func (UnimplementedCdhsSmfServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCdhsSmfServiceServer) PrepareUpdate(context.Context, *PrepareUpdateRequest) (*PrepareUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareUpdate not implemented")
}
func (UnimplementedCdhsSmfServiceServer) CommitPreparedUpdate(context.Context, *CommitPreparedUpdateRequest) (*CommitPreparedUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitPreparedUpdate not implemented")
}
func (UnimplementedCdhsSmfServiceServer) AbortPreparedUpdate(context.Context, *AbortPreparedUpdateRequest) (*AbortPreparedUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortPreparedUpdate not implemented")
}
func (UnimplementedCdhsSmfServiceServer) ProveInclusion(context.Context, *ProveInclusionRequest) (*ProveInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) VerifyInclusion(context.Context, *VerifyInclusionRequest) (*VerifyInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) ProveNonInclusion(context.Context, *ProveNonInclusionRequest) (*ProveNonInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveNonInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) VerifyNonInclusion(context.Context, *VerifyNonInclusionRequest) (*VerifyNonInclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyNonInclusion not implemented")
}
func (UnimplementedCdhsSmfServiceServer) Canonicalize(context.Context, *CanonicalizeRequest) (*CanonicalizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Canonicalize not implemented")
}
func (UnimplementedCdhsSmfServiceServer) GetRoot(context.Context, *GetRootRequest) (*GetRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoot not implemented")
}
func (UnimplementedCdhsSmfServiceServer) SignRoot(context.Context, *SignRootRequest) (*SignRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignRoot not implemented")
}
func (UnimplementedCdhsSmfServiceServer) ReplayLeaves(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayLeaves not implemented")
}
func (UnimplementedCdhsSmfServiceServer) mustEmbedUnimplementedCdhsSmfServiceServer() {}
func (UnimplementedCdhsSmfServiceServer) testEmbeddedByValue()                        {}

// UnsafeCdhsSmfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdhsSmfServiceServer will
// result in compilation errors.
type UnsafeCdhsSmfServiceServer interface {
	mustEmbedUnimplementedCdhsSmfServiceServer()
}

func RegisterCdhsSmfServiceServer(s grpc.ServiceRegistrar, srv CdhsSmfServiceServer) {
	// If the following call panics, it indicates UnimplementedCdhsSmfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CdhsSmfService_ServiceDesc, srv)
}

func _CdhsSmfService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_PrepareUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).PrepareUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_PrepareUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).PrepareUpdate(ctx, req.(*PrepareUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_CommitPreparedUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPreparedUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).CommitPreparedUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_CommitPreparedUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).CommitPreparedUpdate(ctx, req.(*CommitPreparedUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_AbortPreparedUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortPreparedUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).AbortPreparedUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_AbortPreparedUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).AbortPreparedUpdate(ctx, req.(*AbortPreparedUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_ProveInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).ProveInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_ProveInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).ProveInclusion(ctx, req.(*ProveInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_VerifyInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).VerifyInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_VerifyInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).VerifyInclusion(ctx, req.(*VerifyInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_ProveNonInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveNonInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).ProveNonInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_ProveNonInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).ProveNonInclusion(ctx, req.(*ProveNonInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_VerifyNonInclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyNonInclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).VerifyNonInclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_VerifyNonInclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).VerifyNonInclusion(ctx, req.(*VerifyNonInclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_Canonicalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanonicalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).Canonicalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_Canonicalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).Canonicalize(ctx, req.(*CanonicalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_GetRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).GetRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_GetRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).GetRoot(ctx, req.(*GetRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_SignRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).SignRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_SignRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).SignRoot(ctx, req.(*SignRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdhsSmfService_ReplayLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdhsSmfServiceServer).ReplayLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdhsSmfService_ReplayLeaves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdhsSmfServiceServer).ReplayLeaves(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CdhsSmfService_ServiceDesc is the grpc.ServiceDesc for CdhsSmfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CdhsSmfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olympus.cdhs_smf.v1.CdhsSmfService",
	HandlerType: (*CdhsSmfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _CdhsSmfService_Update_Handler,
		},
		{
			MethodName: "PrepareUpdate",
			Handler:    _CdhsSmfService_PrepareUpdate_Handler,
		},
		{
			MethodName: "CommitPreparedUpdate",
			Handler:    _CdhsSmfService_CommitPreparedUpdate_Handler,
		},
		{
			MethodName: "AbortPreparedUpdate",
			Handler:    _CdhsSmfService_AbortPreparedUpdate_Handler,
		},
		{
			MethodName: "ProveInclusion",
			Handler:    _CdhsSmfService_ProveInclusion_Handler,
		},
		{
			MethodName: "VerifyInclusion",
			Handler:    _CdhsSmfService_VerifyInclusion_Handler,
		},
		{
			MethodName: "ProveNonInclusion",
			Handler:    _CdhsSmfService_ProveNonInclusion_Handler,
		},
		{
			MethodName: "VerifyNonInclusion",
			Handler:    _CdhsSmfService_VerifyNonInclusion_Handler,
		},
		{
			MethodName: "Canonicalize",
			Handler:    _CdhsSmfService_Canonicalize_Handler,
		},
		{
			MethodName: "GetRoot",
			Handler:    _CdhsSmfService_GetRoot_Handler,
		},
		{
			MethodName: "SignRoot",
			Handler:    _CdhsSmfService_SignRoot_Handler,
		},
		{
			MethodName: "ReplayLeaves",
			Handler:    _CdhsSmfService_ReplayLeaves_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdhs_smf.proto",
}
